apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    releaseName: traefik
    valuesFile: values.yaml
    version: 10.19.4  # or the version you want to use

generatorOptions:
  disableNameSuffixHash: true

buildOptions:
  enableHelm: true
