apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: smtprelay-icloud-credentials
  namespace: smtprelay

spec:
  encryptedData:
    secrets.ini: AgCPxufO1uB1lf3m/9kDfnLQ2LYY4rvawI7avr7zQU/Xz66aWGWz8zC+hte7s6/LH2VMpPVG4KakAs6dowp0PIiHw9NAXjVDbwccS+uZaHuqasuC5rwO5h1RodkkXLFf2k9OxZbc0qAliTyaRCqA+NJ4ZmNEph118xFWcHUYhi7QhxK1NBCxet0hqgQDTbzd9kW+lvXGk0FkJtp14He2c3TOZ/uNJzGrXlJStwcviUx6sQC5e+GMl8BofFWIzCcnzYPxby0z8pUzHgMXQHXMs2faK5m8rGqZGkYukrZ0opDsZ8OhYxhUtcxO3tNAg2zpZDckRCATCJVmtb/HUd0oKZbjO4v+FtVjor2T2PsXvnHUPAfLR4NhPtoYo5Sd+zTV5jVYB+wpgIiL7aEh770sRckbLSjIB0GzuEA8A7vOPyO//xMdwYTIHgWs4UWniYzvqdNs89mFviaKd/f7Mo0vbt1imaYAnnFzbrMtr/qjfWatVdDZWv15Y16viGN5+dd3D+a3UexLe0DULocbpY/KQgQgPKFGTXWl5okO/5wMe563lmdJof3grQ5v0H4UMZbq4WcnDtI+ubeTVGiaPwMS05b96eG6rftt9TP2s30m8uWAG/+xIkOci0gJ2MUH2rXN0b87eMupZXP1fYnClf/2S/slTQA4I45y6x33PkdWKRGU3wFA30Hz2mJ8iMWM7oVaUUvW0xKA6EO6rLxfGIPsfPaPzWsiOkXhFbPV0JeGl0BCXN2Gmhs9UQg9f2VIe9aeTXS+gfk9b3GZmVEOjJiCKz4InBJFaG0NAmXNxg==
  template:
    metadata:
      name: smtprelay-icloud-credentials
      namespace: smtprelay
    type: Opaque
