{
 "title": "WARP Charger",
 "panels": [
  { "title": "Zustände", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ladecontroller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charger_state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Fehlerzustand",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"error_state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Fehlerstatus über Zeit",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\ntempTime = date.truncate(t: now(), unit: 1h)\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.sub(from: tempTime, d: 12h), stop: tempTime)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"error_state\" or r[\"_field\"] == \"contactor_error\" or r[\"_field\"] == \"dc_fault_current_state\")\n  |> aggregateWindow(every: 1h, offset: -1h, fn:last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "DC-Fehler",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dc_fault_current_state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Schützfehler",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"contactor_error\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Ladevorgänge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Ladevorgänge Gesamt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tracked_charges\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Ladevorgänge im aktuellen Monat",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 10 },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.truncate(t: now(), unit: 1mo), stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"topic\"] == \"warp/charge_tracker/last_charges\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charge_duration\")\n  |> drop(columns: [\"host\", \"topic\", \"user_id\", \"timestamp\"])"
    },
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.truncate(t: now(), unit: 1mo), stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"topic\"] == \"warp/charge_tracker/last_charges\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_charged\")\n  |> drop(columns: [\"host\", \"topic\", \"user_id\", \"timestamp\"])\n  |> map(fn: (r) => ({r with _cost: float(v: r._value) * 0.2937}))"
    }
   ]
  },
  {
   "title": "Ladevorgänge im letzten Monat",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.truncate(t: -1mo, unit: 1mo), stop: date.truncate(t: now(), unit: 1mo))  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"topic\"] == \"warp/charge_tracker/last_charges\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charge_duration\")\n  |> drop(columns: [\"host\", \"topic\", \"user_id\", \"timestamp\"])"
    },
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.truncate(t: -1mo, unit: 1mo), stop: date.truncate(t: now(), unit: 1mo))  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"topic\"] == \"warp/charge_tracker/last_charges\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_charged\")\n  |> drop(columns: [\"host\", \"topic\", \"user_id\", \"timestamp\"])\n  |> map(fn: (r) => ({r with _cost: float(v: r._value) * 0.2937}))"
    }
   ]
  },
  {
   "title": "Ladevorgänge aktueller Monat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\n\nfrom(bucket: \"telegraf/autogen\")\n  |> range(start: date.truncate(t: now(), unit: 1mo), stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tracked_charges\")\n  |> spread()"
    }
   ]
  },
  {
   "title": "Ladevorgänge letzter Monat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\nimport \"date\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\n  from(bucket: \"telegraf/autogen\")\n    |> range(start: date.truncate(t: -1mo, unit: 1mo), stop: date.truncate(t: now(), unit: 1mo))  \n    |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tracked_charges\")\n    |> spread()\n\n\n\n"
    }
   ]
  },
  {
   "title": "Außenleiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Leistung L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_L1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Leistung L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_L2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Leistung L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_L3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Stromstärke L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_L1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Stromstärke L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_L2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Stromstärke L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_L3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Spannung L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_L1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Spannung L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_L2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Spannung L3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"warp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_L3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}