{
 "title": "2. Erdgeschoss",
 "tags": [
  "InfluxDB",
  "telegraf",
  "knx"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Wohnzimmer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ofen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Wohnzimmer.K4-L1.Ofen.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ofen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Wohnzimmer.K4-L1.Ofen.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ofen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Wohnzimmer.K4-L1.Ofen.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ofen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Wohnzimmer.K4-L1.Ofen.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Küche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Geschirrspüler",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K4-L1.Geschirrspüler.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Geschirrspüler",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K4-L1.Geschirrspüler.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Geschirrspüler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K4-L1.Geschirrspüler.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Geschirrspüler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K4-L1.Geschirrspüler.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Haubenlüfter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K5-L1.Haubenlüfter.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Haubenlüfter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K5-L1.Haubenlüfter.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Haubenlüfter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K5-L1.Haubenlüfter.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Haubenlüfter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K5-L1.Haubenlüfter.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kühlschrank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K7-L1.Kühlschrank.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kühlschrank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K7-L1.Kühlschrank.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kühlschrank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K7-L1.Kühlschrank.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kühlschrank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K7-L1.Kühlschrank.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backofen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K9-L1.Backofen.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backofen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K9-L1.Backofen.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backofen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K9-L1.Backofen.Stromwert\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backofen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K9-L1.Backofen.Stromwert\")\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tellerwärmer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K10-L1.Tellerwärmer.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tellerwärmer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K10-L1.Tellerwärmer.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tellerwärmer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K10-L1.Tellerwärmer.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tellerwärmer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K10-L1.Tellerwärmer.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Mikrowelle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K12-L1.Microwelle.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Mikrowelle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K12-L1.Microwelle.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Mikrowelle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K12-L1.Microwelle.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Mikrowelle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K12-L1.Microwelle.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kaffeemaschine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K13-L1.Kaffeemaschine.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kaffeemaschine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K13-L1.Kaffeemaschine.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kaffeemaschine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K13-L1.Kaffeemaschine.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Kaffeemaschine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K13-L1.Kaffeemaschine.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dampfgarer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K14-L1.Dampfgarer.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dampfgarer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K14-L1.Dampfgarer.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dampfgarer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K14-L1.Dampfgarer.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dampfgarer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K14-L1.Dampfgarer.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gefrierschrank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K15-L1.Gefrierschrank.Betriebsstunden\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gefrierschrank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K15-L1.Gefrierschrank.Kilowattstunde\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gefrierschrank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K15-L1.Gefrierschrank.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gefrierschrank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Strom.EG.Küche.K15-L1.Gefrierschrank.Stromwert\")\n  |> group(columns: [\"_field\"])\n  |> map(fn: (r) => ({r with _value: float(v:r._value) / 1000.0 * 220.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}