{
 "title": "3. Obergeschoss - Alarm",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Badezimmer Kinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.Temperatur-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.Temperatur-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.Luftfeuchte-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.Luftfeuchte-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.CO2-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.CO2-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.CO2-Alarm-3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Kinder.Sensor.Taupunkt-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Badezimmer Eltern", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperatur",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.Temperatur-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.Temperatur-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.Luftfeuchte-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.Luftfeuchte-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.CO2-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.CO2-Alarm-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.CO2-Alarm-3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sensorik.OG.Badezimmer-Eltern.Sensor.Taupunkt-Alarm-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}