apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into Certificate, IngressRoute, and Homepage href
  - sourceValue: node-red.zimmermann.sh
    targets:
      - select:
          kind: Certificate
          name: node-red-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: node-red
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
      - select:
          kind: IngressRoute
          name: node-red
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: "//"
          index: 1

  # Inject storage size
  - sourceValue: 256Mi
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: node-red-data
        fieldPaths:
          - spec.resources.requests.storage

patches:
  # node-red service with static IP and BGP advertisement
  - target:
      kind: Service
      name: node-red
    patch: |-
      - op: add
        path: /metadata/annotations/io.cilium~1lb-ipam-ips
        value: "192.168.10.33"
