apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-secrets
  namespace: crowdsec

spec:
  encryptedData:
    csLapiSecret: AgBIt715B2HZcGYra1Bon6sJxH+IXjrDGWXkpQUmEduse+V0+EKWlh6KfGkVWAEQsGilOHWIYpZv4xikOttFB5DHr2WsLhObr48N4OlfaraSrSiBrjZkA9rWBpvIqQkhl/+oJxTLxS46EE1IANRJczW6UU+HMzn8y8tPTs36dwF4WPJJZ6P8EnBo0oZuUtbQIGncONPboylV8hFXPM4re8NknUTosDgpTthCrfMuT7ZqlIbfix3VXp5casKkYlqDSiYSp3u+HhO7TLolLDdT1+cLoxd2Mke2iKVskWCAfXK02pdU2/RU/1LZjQ+0vw/7YNurBzr56YVMb/Q/bMLY6yf/yEV82mPxkQ/I/dQD514P0Tn9YgLY7BO8MBNQDN7usgBnuiY/9ZY3M/cGsKaPF6sfGQRV5cPe2dM9IpRRy+6gu6dYrolkeojlsDhj5m21xOI3oovljz/gY1xVlcU11zXsMcGm+9GVa3po3tnChwti39Hrj9GgGv+qoVhJR5jNl9oIJWv2mnBqD1/Ei8T202v0ttm2cLNBDuAzjrSvm/02vNSY/DMg6B/Q/13DGK9h7DQjcL4rXTlHXapvQ9T94SYcNiTCNcNBBaBP3ZKgq58+RUhSki4qItGn1HlGy0Zx60PMhvVSDnJnKyPtLty7NykrrNy5id5zlF//jICcI7pJRXv256rh1KtZzndxLbGlh8pTOSFsvQkpkjM9MyrOxxHMVmodLE6g8b2G4wwYxJtEY9ctZ2pWCtG2LaHA0QZH35H3CXY+LGxvUY+j4+WxsL++
    enroll_key: AgAIdGwxQY/ZH0xXKQtz+Oo+CY2DZXN1bL6+RTRZsK4w0LFy7/zaKZlhVssk7iQzpG4MbW/hcUADODYHQqrSnzkwhOAssVNrsvtP20bA6FlMEzyKnA8Z8YUE7EOLiYr7eKIAKBJPk+K038ShsuEXU87u1Yq9V0IKRKwSzlsI/NqZ77uIbU3fuGhPizcbOgWnltzGHgmKOEB7jq7jR6a0RGxz0fH7dJUBxhdTAZpZDhzPsFEexgGGe0K0MS0K0FI9lIq9EA+Og4Mg4JpoY90gmccdjmRuHsXCYbg8OniaMds/MOD5bnBt/ycAr1+/mNNeVq989G5X69T/nXhp363VtOydaTFSCECcdeOoOQSwGk4vUniwzSIFCuXXHCzxCsFd+Au18IkjLWRZifUSlCtvarMgFeKdAWG7Q/kjCytJwaLvOVJLuDJEk/veLMiAoKBw6GPacJK14iD4vt8h6DnlGYPNu43Am5tV69P5NmgTLIpfNozqdxNNAwTDtACdNfYG3viuaF5rXb9sXJCLD3QOtPMT75Alp0MKAR0VgoX4dQGtg35x8Y5fuAdMQF4kMll+ArTQ/yr2dE3FS018ZPL3kZR3gyrzdE/V/L3c9BPXDhga9Y8lliFN8RsmpGmExXgCtHEDFynDqJVVZ67QP4xwfntjMtu1VYOvBqBjwa9k73c8+mUSHUksb1hiVBZKKaJgSMHJb4WsxalJNRkNsPeWRQ8u3E2tTQaUOtDB
    registrationToken: AgAcXi9G/COftyB+AfQXp5Gtt5vE0dV47tAP/21/Rr5VLrz4XbKE/q6Qta1nUTrkegHjPJEQcoocaU0kzIrSy4P6Zu+TN91M710+dzyy0qe9ryeDDLUvWKKyOexuePCojFcFyjOYzqQDnRAeC8eODx4wolYwaIq/O3bqArCI7F7RktuMqaXVgDq5Onf2LcY1wGq1Uy65ne54UKhjgwJagqnTgOKSXzeJdOqsL1tuiY9ryKWwrzSqWWPcuKxEqJkrApwYxbarSq8jrCgqMHKZ3ZMFZ2QU19m81tMnZb0L7VC9RKGMhFA0efWF0KYWPmtTGfk0TaIkrM7FwKA/b4JfwHSmW5AWsuyRS+m3ZEVZaddkrg2yKzZvm0ZMXeP9qeAPp/a7yhNPJTFAIEqQ3cN1fZgHWa07lqA7tLenmE7T9J87wciW6yFwi51U+8zd+bxzqc9ibXFT83G7cuM5LfHNHju/RbZEhHnNvbXoyaBDWTeyaPe6sVOfoJ/IepUqrQNrbQx4Byl/WD4ys2GdCT+lgQeI0HeqzsvxgZyI313qGNs8qMQ5CJxJ5sGmZpmXW5OhlBhht2oYHo7ZTku7cUOYNdGlDqvubMAGVp/T2PSlk5jEpQt6RYKJPA7tnV6sykgqRXdHLNPSHRwPohCMpFuhUfgmbUWXPo/4UZDCqbUUxN/OX+aYwu1c1q3t4ZsaaVeWnYCH5IH3oApTGOw6uf44z1GryYf7mON8MZSXq0KcICmqkWBg1qkfg4Lucujzmw0E96E=
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-traefik-lapi-key
  namespace: crowdsec

spec:
  encryptedData:
    crowdsec_traefik_lapi_key: AgAFOyQGR7qL45nVih+SIKnwB11hjah7gozK1O+4KGwHobHsyGIcXKZ3A29irPHjJdSkqMVGmiFzKKt4Mfo6Lx4r9+TNcKnj3hd6wq9kQt6dFfc5BZULgx+h7BicCx67lEeGPsDzzcytjiePyTVB3FJUS1UZiqi8l+pLffbq1s/yGnH2i1Fmg7W/1TtujSFacOLb2R7H/dENa9YpSISS5rFUpZfs6Xg92ovIfs6jbT/CrDHRhw6Coolf/M6Gs39oY5zZ0WL2Ivse2rV0IwSmZ1oAAcsCHQJO9DAvpzTocuP/+zg3KmWfdnnQRPurOBsPr10emWZO3zL6PZC0ngxikN5RNLf6pMj5Gv4myKmQHxKQIbl+YY2vo20/NuaaF9Hu8LVjjJdeOnkRa5sxaHdHNns6XaUT4Gj3I+7m5CL1fajeUBqznweENDiP96DWniknCIGmS4JcRA0CuEwDOxCDq81Cwhxay1v4sNEdsciUouBlQEDS/N8AdBO0wHZ2SJSw24XXY0L9xntfk4CmFhTwLCeykzTVwi6ZSFOULCA4coRX3sMxlqWAs+z9ndKqEMNvondYg+lSEvK3vybvNMJ4VOLnXkQt1tw7mUgzd6MzcAAE/CWeUUOUUd9EZKI046ick/EEXVVqKzc+xvjvjtfooIoGawTrjf5gjfnpZMoDQUa+CW0+lIEdQe8ez+volzNyWQtV9WLIZlra3O7GWq/cXKXkBKsQWO5TWIvYmZP8A99N6J7KA2n3dGgpmL1vTriPHCodUTPwGQhz0aiXdYpjy8Hg
  template:
    metadata:
      name: crowdsec-traefik-lapi-key
      namespace: crowdsec
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-homepage-lapi-key
  namespace: crowdsec

spec:
  encryptedData:
    crowdsec_homepage_lapi_key: AgAJx/IdUfY2sV+u4jU+/R8ODSGyK3lp46xFDSIpf8YFuUMTd3oJeyeUU4EYh0RebWihnMPBKBvOT3njLXsxycUd8Yi+wUOfRlw2wXTR4O7f3NQAd6IGsVzC79TRAyaJnj6C8KoAzNfE5YifEmvUSWvTdokG0UoyExG76zctbBP9CvzrZ3YpmMXvwQXrDoSIUZPPZRVmQb18iXbfrNe0Grv1DDN+YC71Ob9gxvbrq5KX7Rx2aS4ffPg4NYSPDVfAiMMTy994C40CDKAzUhMEY9maWAZqCtRQH72xNIGeWsSitSA/VqayXeg9mhwqujOOC+7DcFfdLD6kfwv7CasfMg8+cmB7ZJYtTW6UoLVveo2NDqmS+1q9EoBQVG5UBUf0emJEugdkLiIjBmUUz5iQzf0OyfQxCPTf4gF55D+tMNuuI7toEc9aBKULTkEQCV4Z7MdPxH1agTHKHOrhhGeL7A0+XrxMzLGrJEYsLPNv1pU5Z0hK8/iPWZQmvf6HkYxM4T7H4G7yai7DAzrL5D8RqHZ6GexvKY0SjUcMzfhy15V9qf/dV0sleBl/tIUGbVGzBk8/p/RQCKX/q+zJBnk1U/C2WbvQwkDryBd9dI8LOyNvXlVZsDrF+fqD1/EgCwwBer8CHiCK7YVHtXDrjMdKoFwXGlKIEZ+NtoyFTeLK1uKeKQxbGXaD1juIWklReS1uclcSqF2qfZ2lvTPH/luy55KDecPQfyU0jDPnaEqk2gkQX7KanbnIq4EyWqnNik57X8Ra92d945gaXrM7VFrDLhtP
  template:
    metadata:
      name: crowdsec-homepage-lapi-key
      namespace: crowdsec
    type: Opaque
