apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-secrets
  namespace: crowdsec

spec:
  encryptedData:
    csLapiSecret: AgARYPM6px+SwZc/wU6m5NFdqzwAQidvBI9R40YY/UdflMPftITwiJSz/v12kxS+VaQGvLKm4bSFFGe35orUWUkYN1RL6tm64cnFDO3wGfv3FdOnyBINEqznRGterPv1n6bg651VBRNWI2wPA4NpRiFx7eEjumHGLYNnK3OdSURZRI1M+tKuQhnfPgwgHcY6NejQziQCtNJ7ex0mk1hAv2idPGQb31uMk1NRVDEzWs0qf3vleliLq31oER7O2EuJyI6+whUt7sEcEXOOnvHeZLfxbNwiqBGA5M5ulYI+5ZJsrhUuk84slNsT4aS5LJ4/uHzmOMwOe6DxPK9LwdNfSbnYQxr8iKzxLgjSol0MVROVx/yVqq4al3lLD+VUd9x7G5j56Z0kh7HoylROFzk8Z8Wlp0jvZp7UzIu1DojGzCZE/MmZiVRI/mebTLwzDQmLLnlysjl8HdtQxhR4gr3WkD9FUwtambP0PUSgfRxxGWdr9zrHtu2WEJgHj2XHh2lRj+nyKWYaoJZ1gtdcH6y1KCqyNMloSCA27eNa/cXULLySjmTQSur6cpUe85fnqOU/bqcv/RXjOQKKP7+zCHxUKKZAUay+hGzHFSm47X8pDjZAQ4EzgeglROPN1Io9oORB8JE5OqG4S49VcvOzpTGuyFeY5DjG0VVtdaU4uF+WGvIO8XED8GWMfUgofAtB9PNtJ0KnNx4YwLSUKqDfIl2SKKeCW/thAEsczyVjfNr+MpX72vD0Sn28AU89jyjWOBL1vGLASE8axVlqD2NYqfFiQlAc
    enroll_key: AgA+wZLksY5SkL32eDZeULAlECfpsEUtadDgxmcwxff1cAFHXRSrFTF2HyLjfS32k3Ix+awbkhWkpNBRqhEzabPWMsjMS/vQ+A8jSmu6HEGROAgwXQ9G0Y8lND1RpNCThHychbxurrW2ixqNtwhcVyVIfXUIsRge27pA56eQRKRfRq2UJFwLym4xexEUcEzrvkFJ8T5tipSiTv8Ll/DZmmItLzCxvJVmVoLH5P0YyLQDUbacP8Ee+kJB/lD2l5FrqeIumK0p56PsPAaCTFHfUwkVTB9FGq8KjbzExLLE3z8eqX+56jj9McmcNOFXWbvarP/A76wGq8Al3xy9oDcD9cYRal6mY1mPkhwVlEutSLV+RQnxrHtLZ0Ar2U1+AohFOTmUOp5kK/MYBUobuSENtHcsXQoQWOMEY9DzOSZfEJPbLHvCVHUXJPqhSz8MVUGVhtEIQt6nSrELQmqss/27a41K/GmbiL//rEVzVy6+DfGFusmdfHZ7MwDWyK1Xa8NJSKfF1o027OBQ45pfcjkbr+UzeVhgJJF5bTC+Mkz4Z8r02GMRGsx+aOK58y4GBzR8rloSFUpdK0JTz48L2/1qpdbzw8Pp9xVJV2WUJ7LZA40NXOV8xRmkSy5ppdRLV/2N220gd/PJk+aGruCY5oY4f08rV8vAx3Z2yTsSawcL6oMZPM8kh8Y4IX/Vr3Lc50fc68OvhrqqulZ+6SIR07CpDCstFgDCIgjzwM4H
    registrationToken: AgByvw/QD3rhHwQEhKx+yGBhJiJwsb3acgjcGrkamGa+ovcy/t1cPkCBuwGImxIXxn+txBgBfHVmI0uVAc53almzjJ6Tq9xJRXnaAoXO03tgkS/njdZT7LvLXJJVQVBRbAJcDZF0vl9+vT6C5RYsL1V+SUxyH8z40v4qvZdZnOHqWqoT00I3rbBlEAFdWKAPKUdgYnBtDvgAmpXA50bGDh40R3926RlHUAz0sauwANSosfrFA148++Okp0i4c5Z1MvNxzFfTwqrj1mpiXsvACObYgPqwAAfkRhjyfrYviSkQdnu0bFag2vLN3/WWG1GtlIoVXLykFSTgK7/zCQcT2Fx2iyd3W1f6r0/2qopFPP7kQ1+jsicVg6U/nuLpXnXFCfa2jxn3M4HMo/f5uLBRjJDjgv220qeKtCTl0CtrHd3JfmmBielIUYQKbHETj7HByO+HCN9LisxG11O1AAxizcXiF9pOZB8gIGn3VQ/b1ZUqd3eLlrl6RLSoQyksmcaSKXh9WRtzqEdh1jvKOe8a16JLXq9BW/+GTu6sBipmggP5/EWbHpbPFJiCHuaukKqxzcSsoOXvu9EaozegQ/IU6KKeEY2z/ovfIWU0q7A8QqGEBc18vekzeewHtE0FKBaFDeb0lpnU16310nm1TqXmP+qqx/K7moySatB5rYN9fI4FgEztBTBP2Kjbsf1oyU5yBVnZKsgeRP4DUFucnQ53tbZTKScwyVlm7T0HqPSPDtTqHQKQZikv7qzQGavUorwcr4Q=
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-lapi-key
  namespace: crowdsec

spec:
  encryptedData:
    crowdsec_lapi_key: AgB427JkVNgJXYS9RfzTbVjMN1pml1ab+3G4e/qXLQNbvLeFgAvd3Mzk5jf8DyFguo7LNd82pJ57HeFN0Nn/hRIN9sE1wQieK8W0E1dwJioiC7apQxVGj/IbNrcaY1LO00yPVoOB9MLRuoT2wpsOFU3ViiTKXV3Uf2lkv3rZBLFRC6aPmTPEDLzX9U8vAvWp0P0FTzzNBVPyfVyRFRwG8IP2QOaBHI/1ufbJPUV2NvFjj5pp8c+sI+n71P0Gi6Wo4HNcS0tHIvq1lfeg7Jj6Ht0HSsqhrg3kAzVEsrbpsuUzj7xmsOElSaMJ2ejlls66HnXWGrW8kIcGhQDw5g9ITMt4zQrRQSjQxy7j2Wt10ZxjRKSEPjf7kEqrCIEcwRwx97GV1/MRxrT4wS8T/P09VfwyUkuaa8o+DdJu/qboNFTxa+vEP0e9W1ScOhiYEaNvymszDg7wSUnfVT+zeP/hmJnG6VnR+HBSA3k8ZoDcyjA8Nw5M+jzBBJL3Vo+W50MNwunOv5kOR5hU2KemgJ5OVGN0pSUTPsv+IfDYlY1k3S2bvfOJ35TqiG+XLfGRsy7pog78L4OSKVTWDspRyvpFitsUXt3UjrioHsSKzqviuMEuLzAwR8Il6GJJD44fqs4B7WbYURcbPuE2iDfm28eVWMCR54VTddR/PtIbjdBQvMX+R/N5sfZQioSp0jZosHbNx4wwrOb2X5A+NqM8+rfe4wL/H/Qg2Mfmd4svESBKewPReV3GU+VgKFKQrzzUDUFfsGtBypCpW91syibzd2dvC1DR
  template:
    metadata:
      name: crowdsec-lapi-key
      namespace: crowdsec
    type: Opaque
