apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-secrets
  namespace: crowdsec

spec:
  encryptedData:
    csLapiSecret: AgBWDXulFuLB0qy0I/cXCRK7Jy9fTj0DqJdVMY/2E/sTfeRY286nhWcSzTWMEslaxdxFiEMzsfDuR0t6IjqEpGRmz5439yojP2u9UY6N1Pqgg6N21J9Lcai09KEj6fc+8VB8axMdvgk79kxnXC5X2dvn+4hQBfFjpiju95jq7Sh1CS4FWQeZjvaJ4wYhaHbYh0BeUTLb4viTMjjOpqy5FxGxO9wXeRaunw3bcZX8uGUkTpywv0ZD77Ed3cRRecdFRf0ILeJNMViRYecjTKX/QpJ2x3fVJFeyEKLbjMgdZ2lQKNhb9IY1EtLm9/BKZDqMBjeAOdqjUExzBMaF9LRtcH89vPotULl1YqTbRxnTorpzp2937V89zpwtjuw6Gb/AxRgbE+bjsEZLXyB0pcotr/lr1x0xRLQVGrNc0vKmQeHNQxT41rQoh1gbExHDjy2R/219vlhQxtQDCQni19rf+Dlqh/z+mgRckxpsEaJg0KPmTI925IZFcqjzsPkUkzCDJTkzxW3tbNQFS7wdiAHyfWR5WayZSw9zfZH+ratZSTy5w7LO2GzyjcdzUp91VMF3S7x7tWrpLuA1RuG+MK9sv5fd2wevK+KtsJQdg+asJgLGGMSqTdvtQkkgmxlFxf8os0nVODMGwQCej29IbZZWLaaOIhAqrU1XakUUQEGRziZ0MlY662UDh0d9Jya7VwYio9WdrOuK6LuNIXz13eH2Mr3Hwku29CvvxRfDtVQ7KGhSjtsSUgZu0xflS0pmJkI53leKpqkbP7omGmHFape0e7KT
    enroll_key: AgBHp/n/2c9dEHp/IPyOSxdCtUe91DxXV1cBUgoVvPwsUIfkygNfK5bVnkeeXA6+tuKxZJ6kbhd1flydQGThPMiALLfqsX/TwD6uoEUuFKNTmFswzilbj+v8O47iZsLoK4Rl46tJMUp1Q52iNjFNJIP0Ncr5wLaXVbOrr7IPnf/+W0AzAl+Wmog6rNDJyQANgd10uTQqg07PUpKVry9tM5sANldxlr6gkhzkp7HJ/8zcSqL2ab1kD533un1FSm7AfXcXpNzhJqmq8nXYZjPQ/0vS9QlkfxOb6LP1fXPddBGcg1pH7m44foVGZv2FOwHQalm2h6F/bruTl43CcNJ6MhCO1jK+AH2GXCmRDRror0ivFpeWJ+lvYQKZjvw0AO7gmdoyDoQGvjHpjvH1tmLZDI9iVirlAgx0pKZUVUARlkTKieGjljEoaLdKr62jJU5s8TFpheiZbD3J60rreKY5cbGwxPzXWjBze3oBTbAAZoBsb4xuCibpNzF3Yr4hHsue7RI7GBDkn6pAJk4R6JQhz0vQVWHd5CjMjqW+dVixL8cuPHwPLZCFpx26MpWOTh2Jcs0vkr7XVsSwFhn1G+bfSE5aouVLvyvpOw1IfF9rCz0CJp+5XwFo6/fdrE6l9dreWzLdv+wEsc71ifeCrl1ugsllVkT0uT1xLnm5M9cMZzT0USy3VfJki++TDEHoQH1NxlcCdh/tNQERnm97ifc/y3ZPq0TH4LYsFh3J
    registrationToken: AgBS2YpjZPD7/90CN9Umn4GhFNAKZKvBCeNIhEYbfIFI1+hksYkL/wRe8677nqzw5FhdSQdwa3xWgfXSobh9r7hlDx2GasEsQVmYqwKU7VMG+8CKELO6GFTLWH12e7xPhkpvCEftQ4O1rWG8R7wjp6H7nHrBxnPS3cpo5lEmZvxBvgLZF4RByhO08iGPrbodnDK5alUyGUxnZCrJIm6h/JKUxL2A9JQGVsevDAFXszU/mrrNfhht5v9GQkn16LvRSTOmHKiPK+paLStIhmoy+5082e8dfzmzKdzJPHqHTZDo8WkeJoxX6WK4nXE7j8Xwbs+8yqWKzzqZ3sa2R1iQIN96GGIpNIzWpF14uLnNkTBYYo7lYdRSd6vxrom6JjTg/gemTj7txOhes0d1ZkQV0Egq+IWmC96ta/mdiTsYq54PZQl4/Yg52SBlegXcTLvbPdX3nZQqSb4HfTxogMqqEz7ROfl0QH99suaBS90SevChAGUE+5eexaMZx93UipTvktu+IWp1i7cgV1gRPoduhyW4KV3p2AFV8uAAxBhra404eTI3Zu4QVbWK+bSraRSlr3hZCyeYt0ED8qwJG534SvGY1e+9OEgA1G2rWlfqEr+NL2mNcUwZ3T31rfuYyG55nl6WjaFrIUfD0mEubNt5/BkUkEW/QU/Vg1L3y+lNr+EOKBgNuiWWPG8CaClNtP6duYfW0W/EGFW3SlUEpoiT7kF0bc4AuII/N/5pF+sCVnnGo61dDQwaKdbzboLi0396KsI=
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-lapi-key
  namespace: crowdsec

spec:
  encryptedData:
    crowdsec_lapi_key: AgB4zZftE+zWsaA8OwxIUS98CHLEFkn2kV0D4rp8xKZNoyFx/Ed693AXJsLGYAFpVs3/6ko0OrjaGSbXYtxM6uwvBuHlPnBii0DRDIiMapkaPPEK3X9TLsB8tlHmtwXqm0iekk7NlS5X/5c7C8wGUnHE39jw7nI4J/QQQ0aBiN5VLuLJ5F3MbFAKwy3dQENa8ZcQg/Cn3pSLpXS4v4hbzIc2EvED2Bl8C7ei8/wNlOAnJAFDUzjb9+kk8cAGEDA8M9xolmqwXB2dUYFuXN5vvgaTNWQQA3bZaLaPxj6qim7Rr5uRAlP7fljhwXeJ+75cyfDJqtZwTrUU+twv6ROhXAxpSJwUlwVaktBVD1jEAhbunQ7/V7Tz9HFh7U3Iq8tmYjKZJtO7Cth347PFk7pKHhzBDL4xY/nM6AYASMOXKznw1ctmEZUphpuGmc9rFzyEeDaA4QFSk7uHD2wZKvDqbG9c05wJPHQgPPQLhDtZzJCVL0qO6RkrXToCnTHW5u+ru2crEPRBZk5xb5EBNbK7wKMesegEh6Fzn8HpW9u6URoQRLHvyacMK+8ohSb2tCPUi2bq0AjVusO2PKTtQWfO2PUTiXeD2xGljgpixPSPgUbm8JvVpWpl8aqC12v0pzmG4AUM51d48ELcWpGIHvt7thSBtVsW3UCHq+skn0XfSMR2kHvg9h1pDQbe8EWY/3LQjN+cGU8zsmCZ6H3AJBjQNi6CqsUOAz+7PWD8cm+aEfYgCIT+BHG8RjBebXqdKJb1ULdWj4zPaXtxNelzfs8L8nKW
  template:
    metadata:
      name: crowdsec-lapi-key
      namespace: crowdsec
    type: Opaque
