apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-github-source
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_GITHUB_CLIENT_ID: AgAMj+zfRaKQU64DHVWVgGMlnYFosSyjnWnCYwOfa+3cwR9GOIFIlGYU1nF7h0RMNmC7vojSZzaaZG8rwwEQtpf0FRp4iBucrnFdg0QIK+jHErPhrWFzvtNAZv2fEyO9S+2VMtoyLlZChVAd9dRce+xbqmAP4uPc0Iv/mp4lxaTKxvozLGxgpkZUr/DpgE6riu8IbSvgIwUAM50LXCd0tvw25tnDcIV4Sa8E+Fs5OxXP99iyySfdztVUPqNqZYDuWiMIVzPClY3NFcxWbNfPfYcpL39DCyuU6w5YqM7vD7Zo29f7+RcgJmRl9dXuME+lZTjTDp05u3XVGlLYaMbUWhyU63mYwFdcl1OK+S44bH41RZGlykZzbyDEUy6m7IgSBDb8NqfmOLEaO7hf3SqhFLsx1WJcV6mJEBARZrBpYYLBw6YLK/tm4n4Xf89LZBO23RbqgoSN/HiSFsgCKjgIiMKKkMvBk1CmG+GpzhZJ5WgoYwJlyaBct06Wzwt84QILPVoFXirKtrReIADdOvW0Q4kKppdtE3DRT85RFAU5snkOf7L2jANO3/oBEN2wi9qYwMgb3guf27dWu+JXJeIINWjkZ7Qki/I4vDy5e+1kwLkdaPqm/xXhWSj3258duasvSyc8qtWqtqND006CiDJOudUVF93xj6p1jipr1LhHK5/8dJdtKDk8/TPyMGzXHT8qOU9nq/n4iNLgq5hylre0KQIdq32oDQ==
    AUTHENTIK_GITHUB_CLIENT_SECRET: AgBQNC6vyEPOUzw6/Nc+Hx8bNwCnu8gb9BLoGDnLkVzm/aKLpFnQgaFpOBcY4iobhrLpLsHO+ClVO3gB8TP4EBLBsuvp7HsXjho29v9dwZthDB871d+OH/0n4+AaT4R92GQxFmVw3FwDmKFp/UzIR7/pU79h+yQ+9rGjlwKTw2z1t09qK4CcYKgW7oYlksWcdEm2RY/asZb57NhIl6+HBh/lztRDwm0hWeKjY0AH8biiY6rk0ftpLYQvhljx1C/T+7AwaC9rqNzNnfD/dE9l1CuQTdSQoHy47pi8gynjW6arXFIYCO/uOG92+LiSkohP69/oTlgWbtWy3J1ZMy6PLq9tlMW3s9lELtBIT98gmjGhoR/PMUoVHoCeh6NOzUtpLRWkinl//acKXlSIJNk6yChTq+AkSFoJkz7JJdCUH+QwxU1mT9tI3hHKgBVFB9cHl3wEs11l5cE/fjdrYsQ/QBElUcnCO8M3wUlauOyccxE8+K8wa2xIgsnIPEnON6P1ytjyCwBnP3BxIZvM4sr7xbzQ2tTBeVMmMl1se6LrDZpORABP+j6SeeePcL5URiBxR9lc7P6ElgU7qBgJAWpnpeVrWByD6DUR4Z0OpPZE8jj4WvxXnQeWnrCNq/JqIBH7lZJTdljKsDbnGOk3N9J1KRjcHzStaKosBuD9LTPOHTZEJZolEgT/0ZXEQAjSix7pYCBQ43iaYl2Ok+pIBcebaEAmiUKLfw2cYHqzJ7oc17WzZF2Qd2v5zYky
  template:
    metadata:
      name: authentik-github-source
      namespace: authentik
    type: Opaque
