apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-github-source
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_GITHUB_CLIENT_ID: AgCWf2Zq5N5/zNZSwtfgW0uW+GBuaflj7+mwu394ZUDLbZwQ2JJLhRHd4nXh82WfmGxn72ZSzvJzao8/TcV43lxsgVmK9pUV79JtQRxqhj3UXOfy3JX9G6LjRm58CiNJemVnyI85E6TxqmIw+fRtbt1oA9f2SFpp87QXO0EZTJ0DGYbbzYFrjBDcx/1LYPNRzw5KaR6KsLRTwJr91C275mXVuETngVlb/P1DMpxVvTuSdM1VOWLsP+VXcb/Asn9y7BwO5L6xVLhDAyjlMYl4qHCwLsDPBUOyUpLVdsKfRTN2AyX7IE5su7L/iDlNZYmCqMbcYAySsOgYrh8Ao6/IAh0gpn3xMkKaS/Jv+Pj1HcgpznUoYbzwuG677M8jjr+BhHvLZUNH3k7fcoMeDWceN3OQgMoMWUCZtDLi/b43r0Niuiu4ISdII2HtSOb+hRMHnzTDgxs1cHFuDYisn4jLtJfSbq2IsNIwcID8yl+Ct9gsrnK+ipUcXHTmUGD8gq0tiiR3EWxF0NmEiZJVVBugO/Hlx0sIZDL3UajGkmSsKPiHtRFjpWNB07KRit202BYWv0L3Go765l0VCl2OvMslkmBegCIjVwa31Df8wYVo+xO5VRjMMfGHWJoF0V4fy6QI6M+kapJfUoOfsnszZZizZg2MIv/DeaAmsZKHkidwbTH0fM/WOfVCGQX3DB0YrvbEKqELiXpBIWPp2tMFE/BqSG2w04tGww==
    AUTHENTIK_GITHUB_CLIENT_SECRET: AgCP/uIMTfwyEul2W7+HVmU/J52gIRPxYyaoPAfZ1o/Md2xuSP7oc3DQQcq5O6jjx5fMyWKW28qWi8VxEZRKiSTVK866DZY2ALZko/wOpALF6+NNyYEwHS/V4M/UDheU5BCIOHhZ+c6BjaSy6restLl+MqCOMZ8KzmG185xJOUkQ672y3vzZyw72J4cWPoj9n9ODvE2Ro/v6FcI3d7JJw3S/rBnX/ORoH55BgvD+piaYdAhu946UrLdx/dEtaiT9dla9YnghiS5Gn5/kM+ZaakbbC9Xo4cMoUtKcskW0+59Dgd4vFa5NmyfUq7xiG1CIxvMInEzMAipZBGHq8UU5FVctLG0YotmBt1vEgE/M6P2KWp5ukMSbpL6wpSr91CnzzK6yxSNVWaWL/ey3+x9XK57WCK+FTsr27kZGPA2J/9KjE1JlR3F37bdya/v9uRM7F1LlDs8vvXG9kaGX30LFsqdqyiC1eAqpI4sZd+cMGzdoNvgBKBkMztwhuaIWuADoBVKqO3lDqitl/Evs1UJy5/BFvrc3ifCTZS4qBktW2T338VYuCE9/Bu8HsX+ctXnzEndjcJw6zdd9VNYBzGbKeFi/x+ZpccGEbZK2eBmgDiEDVtzHEvx12LmocVrjp1IAEsgC09mSuPdSm+XGPny5rRVCMvrhDDxr0HhOCFM8frzMsM0ykVAzHsNHJkJJopVpAyJqgJ9xPqnp2WtNR4QcW4SsFOy79NUAIE0oQIu9KKkH/tey7oO3Np9i
  template:
    metadata:
      name: authentik-github-source
      namespace: authentik
    type: Opaque
