ci_meta_config:
  ## Standard Linux VM
  std_linux:
    hostname: proxmox-vm

  ## Cluster management VM (Omni)
  cluster_mgmt:
    hostname: cluster-mgmt-01

  ## Proxmox Backup Server VM
  proxmox_backup:
    hostname: backup-01

  ## UPS Monitor VM
  ups_monitor:
    hostname: ups-monitor-01
