apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: gatus-secrets
  namespace: gatus

spec:
  encryptedData:
    PUSHOVER_APP_TOKEN: AgB8i/Ycs+rt/BVzBuM6QVfYLlI7plIGzMrdFAM18HOv5Y+u3Wr+CgXIo29omIeAOFv+fXs63fyPzIgPn8vmyFdVxNrGzGco+9Ag7yS8f3BK1QW+lROK2042hPu/jjyFS6zVe8KW2ybzjWxEA2ed93tyBT/KZBdCNm3jGcyNsCzWkupi6gYb3783eOqWyQU5NLOhUTNb86mpTWV6X4JT+aXKQfYTuhPcUnv3K3eXLXXJyVyob8pEpTH5BsY1ypxufBkoyYmoodeUUAfvrdFYBJYaPBlIPc1wKhRBI3LbUMdsnY9bBi1yShJVo8HmVeaCmCax2mVJ5qvOkdjWY+sny0v+37UgUQBjzSv6xQpGkyjuSQ16nmP6zIBDYZeP9tSeEMPeoIdN/1lDPkMXHH9UoIl41VW51QGSy+kRcPL4oqxfhHR43BYS/K5ebabS3UTz+4JdId1SlzwZCpAJzp/LMk51RNz5JtbASJwz6HEIiZQHkyZjLtFE7UQOkzf4jJyMfzUTfnahZt7NADnjCH/Te+aiQuDtSYv5gvOTF8H8KvfxZ1Rhhlasd4R2ST8HwA2MLMHGEbCVtLK4BfwU/mjMVCpUDzP59eADEkcyYIRwg+X8eCHJJn8BFhRBwIsfZsVUC/tyDuGXK3ik/10FSi/US6oXWpid8EX6+Bs97NmD7HNu8GPD0E5AMp2uEJCRrDrWO98bgtTIn6Lb/ytcF5B7Km4BJ7F8z/v2UHXhtvFYjLc=
    PUSHOVER_USER_KEY: AgB4PiQgo7OZEqgybGj18aDZI+eLHLqGhFPUYuqos721+7GOrFofMqvoiAd2JdZAyG1P7K6obDogCKEqMJK8JEI/VWOFQrJ92EsfZnIk3I26wBdd6jmy7Wb4x2jFOUVnrqh7MXTOUgSX+D7WBji0RrUg9VBzSHQ04/cTKAS/OAvFi8hfOi2Ocxxi21+zF2WmkL9tW4znEgyZk1J9wERrRI/jvsSAAPR/+AxFh/YfRJhfPECmDf0HHvQkImDJQYhUjGz1OL+m3ObI9q6e5FZZ/WlGleHYujVrpIYTfc59oS2H+UV4Ye4oN1EVeNB2roqKJjcyjMiiEeWpYBi9c2/crRxVFQ64LI8KpyrAxUypOkPqfmQDIYwxheNje+9j3Z2cgqX9hA745kRBh92zlHpfPbkcuKHgogomvAGSgLqYPWq1NSBpjckLHMC0sSDYIegQqtnAQtXAWGmfTt/vY+jbCXrEmny+d+wFQeSGMIBiwVrMtroi1YI6c3VjESkZmL8oip/TzM+eGFw+HwtbwFwKmYZ79bmoySmNFCvMObz/THVLpoW0g0SMnE2TnvRSRHBiwiy3ShiJ4jr4pylypxZCmwVxmPWPo4lc4jxSsKPfjGKRm3VM8jNS7VIpUpTEexhBXo1DHL2OyFeh19h25uc9mJVCUvzlbSqoCUhVLDPOO/Su7EN/idt52AWn0DJKV29qwiM3/buut8K2QTWy/9M/sb8wzRZnStvYkx+is0j2PtI=
  template:
    metadata:
      name: gatus-secrets
      namespace: gatus
    type: Opaque
