apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage
resources:
  - ./namespace.yaml
  - ./rbac.yaml
  - ./persistentvolume.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml
  - ./sealed-secret.yaml

configMapGenerator:
  - name: homepage-config
    options:
      disableNameSuffixHash: true
    files:
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/services.yaml
      - config/bookmarks.yaml
      - config/widgets.yaml
      - config/proxmox.yaml
  - name: homepage-icons
    options:
      disableNameSuffixHash: true
    files:
      - 2n.svg=icons/2n.svg
      - basalte.png=icons/basalte.png
      - mdt.svg=icons/mdt.svg
      - telenot.svg=icons/telenot.svg
      - thinkstation.png=icons/thinkstation.png
      - warp.png=icons/warp.png

labels:
  - includeSelectors: false
    pairs:
      homelab.app: homepage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
