apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: homepage-images
  namespace: homepage

spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: PLACEHOLDER
