apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-github-source
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_GITHUB_CLIENT_ID: AgCOjs+QYiYKpl9PyQjGsBpLP46y5y1v+78WNfwETXqSvCIWF/li8IyZ8FjMy2WNyHADemjMMO6MFi1Hmc7+bfsdLs2nKPsLOuGGZCi+UA2RTDCz6Ri3rUAXI+BXsSKg/WUun/iyoeZ7np88zQoDyxw5yQH5aaSaURyWNgsihQNrYIM1HINwzSrdba/QyVodqt9SJV2cV5QvQo0fGIUhpuADkYm+oo7hVRvTiuzJj381goG0zMABL0eRwx+poiWobKf2M1AFwMTzl2RPXCzQalKn8uf0BiMYIuHt/MUHiQqn9urFxQ3uSnruHlQrEFWssK0gvnXaP57rpyWo5NyKV/flCCdXRTdjOoBcMiGbYR/Chu5o1V05r/TUjjAfjUjeJCcCRc7j/cPvDkJbBrL2uoQoRUsm2sKoed4U1wjZXzXBM/xOTaILsXg5WVFbMpRNlgqYn1eSlZbMd2n6Zwkh8FPTrPh7bdN8xZbJdHEZZjmEsSbUKAWqmQqGDrHsxzt9sVfTx0Pnz4MrrGIiAKPbVOmcW/KybBps9DBfm+pdmrg6Hdsz5uWaUpsUMaJHW5C38sZHDeIuCJV+AIs4X/laoWfPwp0ArNJOMHDq4LX1cGrbyWgGeNjU66jarjxXh1OQj9w2BKh+rdGaXmqlNnv43g4msAwuMDN6GfIgXEQAT9uv0opMabrXG5t/CeXWl0yMD3oEborppuuMKlESGoOTNfV61Ie2Vw==
    AUTHENTIK_GITHUB_CLIENT_SECRET: AgCbcFKWR6/mzu4Mi16/I3AIHKaRUdRR5CWYOnGiVuAAwtgN3f8BNI6L1/b0MV0AOBpzNNF77fjUs0uFOewNJFIOLM9hPpXiMFTur/3EFbd29/VggGsQM0QAvGL0x2vd6+jW2ptakJD8+6kRKfB9cDZwotKHAiQcSmwBsgha4p58tWbuEKJsM8pRonw3MCJmn6wraWsHFPUza5GEMEIFPDqzezh4okPqQnL1SFko4aiPxtvk4VBKi1afjJRE5ITGdIOlgT892z0iE4vD8/UtBEO5QsZ9aFw5rvXRcFF76P+RGhwl/dtgchuK5mafNjjCGrhkxUv2wTt0Ykj44gpfb9HwmFrNsbpXbCbQIwtRpH6NyQyRrhD7oJ3HLIC6A5MAPitSk01jS1+6Rs0ZhOwO6wWLSPZ3D/i+GNeEL2fHo6zOFzEo3d3I/GsRqfkjMu0TF4UyMUDmKZN9SEKJUgoh+MfkTKVr0PRjRunDNoX+WUBMWCB7N8fKsTO5alkDgQ9kvW64w5r/UsrG0bH9pb28CjcpZz3oePhezcTb4QMgsR/NQ/EYRyxSEOKWxik3DXX2cwvOmRtgmBQWAm4KHIhmC2WRPax6WQlnK9LXCu0UQ9SmU9XP5s/SyRdXXcpORgXn5tOThOy8mRH70oir8FGfzhAWcp+xeYW+DBiDFE3zhOUXJiOeKfHuH2nHeSowmhwAEiecPWp5pjlbpb/Kbn+DAB+2UKMAlVXlphZ5ZQlm5j2u5kPAVIS74kKC
  template:
    metadata:
      name: authentik-github-source
      namespace: authentik
    type: Opaque
