apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgArpL99yLVfih5dCO0j2hWs/mvL2k2fLb1Cyhe4/Ahwm4vPxBP8y25rSJhKN/QnXyZ04XPYtIh+8y6sHkwazFAnhrOcLfg6sy9HXkrbO1zZe6KqXOwsikKX4RsGoatSRr967Q2VnUHnNDDC9F6sz316fvJwhi1+xJKqDXta0DDy3ngLSLzDRx1JDHuXa2oZQm31TL63GdIAAz9ICtKZIqnXMaWDWhd+ejTDCr9vdD88Rs3YRMu2wG38QP5gRWj83Byr7LOX6wigXRTntJWhXKlUVV4v3r7gCt5ATFUgutEX9OEdDyzE56qqD4kcB2HTELp//hIV0ysGGvSU/42NQPPI0y/LmxPcoHEZolU8yfQaxy4LQlhVpudHTF532BX9+8w8q+fKcRf35KCES1RY9gg5R4OoyEzDFXA0hlT8IcM3axnfp2ReWs1Afso/Kk6/G/hUkKiAXXBZS1DXpp3cFgu55+S6q5fdkuFb8UX4MCxqIIJYvGcaXEKr6zcLkOR9nIOzTl1Dsq55JpRHaKpMAapw8AILxP8OTpdb8TjGsz5wnEw9XmcspzfbSELtBTiug57a982aNK0OjChUyDet8AsIweP2PL4KkcJIAgu3EBu6t+7svss1uxlEV8CvtGVybp5YzLwjqZaRsvvC1UI1DQ38wM+QnlgHb3BO+5Ir3ar2M7Ql74t9CVHupiLj1PrVFIXPJ6q8VoEglEL4EI3Xt3IJfZPC22tKGtCMOI+p8ggJ16nspY6wLzZhf2hNvYoSRFMdVNaDrTyJf0/lkhHcG9Dp4R1bXUtcEnfOMgqqpFVgp0WeMEoFJ6MF82H/ME/NXsszCXNpLt9WIB5ZKivLP5tHmbjDdQ3tysMvjE6dw5XbNp5IdQX6Q2k6OEoHa5MZ0g3XpEDA+sARpXjjsNGHoiz43Dzcy/sQSFjxOtfQvuicqPnyc2+tmUmSsdxtxTC7g6B1lixEVoLDNHYjPIR2iB7GyuziU6RGyTFl+LPMe+XF9Y8iUzGPRuEPEHg463i2RFp3yWqt0kPVJjXQpn3l742AEt6TIvidVEmAUfADaipEbpC+2enoM716W7tQpSR4TQEVBYZLgghqkKVEQnGU3Euz7x5jgai2f5LDaVlMWyYFxdgCxzbCZSpEWCEVEY2BA/48gbafsc1nLTS4Ow9yhVRhbu606LzemeDFbOwzNpZSD9YYHE3+wEVEX+ndmfwHi+PjAwg1DlC2HrUm2AJmHcPpJ2Mm9H4OKBom7NTMgXD4JvgbB7+QTxewJuQPJx6nhqX2IFL1rwF7f9ITFK4cB7lcvN1lZHCxMxkjwV525OQYtlK9GpiDkMHY4O4mwvO1pgXIS3YklDLXiBld998Nq+kpIPgcrWkolQ62jgBGj9UCG/TeUfOcbYri8B0jmd3+AW+nKoPVaLog7zyygxXknE9ylBbTdf/ParuCzTXXOzAFd/h3xY5zPL9Qwy2goUpmvuzbbU40iu05SlpapYRs26TvN/Jp82/+jROj2Zo9v6ZWyChS
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgB0hYEYLHCHrX3TuM33sSthrDq6K8F/zQasM4tbwoqYh6kyNoWcQNbxd9m58KR4mW7xHF+LVjCyPlalQ6hPNjoXei7rJ1EQ2deu6/pdp4FiUBs1OQnv/ryYQcsA7xQG8NEZJl9mQlgxOaH9T61nyh6v5GbL6FKmtZIXvBVlO1w59EBEhIirvOyr8/tPKum+AqRK8EIUv0na+PPzyDGTUp6GCnuDaYu44rbusGMnqD2fbLPVST8ujDNGJzbtqBxf3+54mROe+8cNCTnuHnMqMRhqf4/ApgalaMj6nhNogx7YfORj7tiKUzOZXBf+Qf4pBbV8F1UrcR5ifEwN7IGjgELeOkEkIKYw8vaBWri99YXlBy9wvxPFX4f3s7alWjyvx2BEjTy74LCyLMVuYy4E90/OVBB5vis9u5F+dUr4BhdEGzWHk+SrUTfNOZXUEWm+4FD6CdUWfOInMa6MG2TVi3H91z4fcW527CFNDBfbIMHcYyUV7Ay7R2YVSLpPu7aj+naYRb8rpB2zbF4Ivryy8GoJDr7jjczM5COCgKFEr9yIQ0NrHc+hycW3tVeq3gIRzK9L8znHbHx4d43KrU3FIxfkN3P+eDnR6R+kpyJeYXIwZghmz/gofE9sg1RzLGe1z48FCXlFWE8wtH2GuahekXo6zzelcaqSGDETFG6z3IMRdRKN0pxvC8EP0miUqmdvXIQpGYvoHpDzRxUz3Z52u86LBw5jhAwTDgYd9JUyA9XVr238ozTuae8yCTb+xGeaI3i0/qlfqLCLZeUC8QBkHixOSVqr5rp2b0vcQqaaSDEo/7pK
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque
