apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgB4iDHDPon09+jtT2kzRqPs0KvMNH2K4lJcENVC/Xs65yTqUBQR0T34MbCSXXKSZTEiJKoxv9yTJjWW/lbzxuNcWqK+aIKXq3HCcjJCPWF/s/l0rmepTnqBiyZQzZIA6AF0WrgPn9Ns9DKUa61XNgF81BeRU/DV/2mGtKs81BxKaSrSRMMS/sRbJZj7QwRTtrFLlU1+ShoK/wLlzhxPdy+F5gQFcSRpHaezSXpcX3S1lKyRFSGF59KIRV12ifLz2wAnnKaF+vTkce24kb4OtINNBc0BGjYNhFnnVU+xzO5wPCWPjfZmJLu6fHSvMnuy+DhVDgdeH+qFHpAwd1h/hTM0lgesnlTRYFkM8tFakbDuXC9FKF8+/kYQ8+dyMkVBvF0VR1Goqr2E54dJOwE+JyMGagG6BTyHurrFSprjujsyD4rse6mu8PLsOr6mcrGOBS/y325s34j9BMv8HYLeQpjIHtN8yI82Kie9u55K45ABkqjevqcphYoBb6e7d+L3HAOr0xexyCckR7B5Ud/a0SnWOTcIDPCAJowrw/m880KZpqare1UGXSPfK2845vFqmWU36cNdKGgIlg13/8Sx0HR4doEHI6JuDs6Gou0i3+nSRI1XCYfs5D9G5a6FNjnmG9rERNyy2yF8/Q4S1F6Ju9o6aWzMv7+V5o7FhpPxmNAKvUdP+AvTsF+Xr7eY9dGdlqBPs1QdP2jLwZNB5jyg1v7/ufhWsqDoc8qKZs49p/5tFPtIMMC+5vjY5ni3AsuXNaRdp+WL8YZ9+Ib6N/G2c3v0rcP6gjweOKLSl8XUXuqlypgCvYsX8PLf70BdKGvrl5j6YanC82J8xQ7a/TI76H/qQEvedagKMi8bLzdntZCvy3EMv+7YtRoIS4CQp27n5NsJQ9uB4j32IYHAh9VOc7suxagrIatWmQ+802921tthO+9CwcWlT2/gkIZINWD4PbT844haatRCg3ZK6gP7QrSTgprxfT6ksBZBrn4q5PlY1wHs6KqPYuH0IiEyvIhOFCqikYjXz/0F26j3ZBPQrn3ilm62PFznKtls8EE4kaKHDnh2ADj5XhJ1XZmBcP++GMHiA+aF7g8KUKrOK+luDjy/KQboE58WhK4DOKDTCIF92NOUNuhvzyNSYmmeaXJgJYGd/H9KjQI1p9dJ7P1cLw5pBEAh4OExkORTCDp+cESzDebwYcFnCLnqHidynREpeW0Wv5gxfW8PrVG3FSUwAyRRzpT13E4xl0R6iueUy4vnUSmkKpOgX/VSkWuV5Dt6ETPgMq3lVsVvQAXGYD3Adm6MrX9cOCMhIHd7I9S+3KjdMqZSlgrmwXAlZQR9l3xz5Dbkz7kUPhRcFZ3c3EgeXEG6bT+qbPjbtRw1XMyyE51yQdaoIsu7EPQCkH5b/HxfUcixlvkzcKk5bjv6/xiVDR8dKJ4RLyrc4isOY1tiGf7EEknKiHe/9R0UCexOudZBsaLWNGm6TLEsVQqh/FNhywp7+Mx8xLlRF09BwUQhhC2jOOoBfC9OEk0gjnNaB75C6WgmQyirEiJsYgbKWW+CKRAWl6J6rBanuorNykFOToQy6M/s9krE5Af/1cT16SVvSpTWhY2sLKKzea+5EQXGFoKKgyqhuNyWEWHcJffYnNGNV8MqKtaeeDCgOWrbeiXd/WODMHqaPhzAgxd2xLz/vFc0sSF75yl1I9h6Tv+qKdG04vEy+jswtUGIDTVtme/Dam/tgWIyuwul+VWxqDpHl64=
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgAbx57t3gYt8JfKbDnkDF8qLzo1t7kVHP4PUPK7tsg/SEDKBDTiwDqQgJ6irk5ez+FYNGEcQZMPfUt0qrsZMlADbTUo1AufcoWfogD3j2giUAryDw2PpLH+CdyLphhII0QAGfT5lXi+3U/YReL/bYNx4P9DQX/R+Tx/PbcWn3bUThFLoY1nXTc/DYfxpCm5RsI83ewpqyQfI6PKnFF+QYHrTc1cu7K3teCtZyw9O/q0WRj15CjV6gcQlNiD5wwX6qxU+iALp84cGrxKOg0AfjudX30qp7rFa29K0nKr+yn5/d/pfAoztAvUzvqX8tFtP7MJi8Ff2KMZ2R70ypRlfbVtXK0oc2h67t+QabW01wIJfdrLi1/F4NJRmXcXTXB2OyGwa3uZ1bsVKsB3yzoU9lzzaBJUXp62F2cFG3smu9UodBDbu+4bNii7pjMgeQWs83LsQW3WIIsVv7U0+Y4OLN5gpBzeFqLURQA0n9OTlroCfwSvwFgQtZhsuJ+iQKe1S2j+tG+VbDHsDwwo7FJdD7d8v2w+P93A3/8ANvCPcbnlFF4M+uHGg5xAGiYokbWUzxgN+t8+peBcSI8TgcKqkcRzUY8nOV2HKmxCV2xO/QKH34H+7XuhfifDUM9j+VTgniOBGKeuNjJBnWCvB4S/GpYYHdMOynDSkuK4v45mcLu5WGqSAost5Zog+9VPUqeNjCPziHLoj8/xnQgr1s+12WMpb00swNtwMY1n3ZjUme08E0mRHaZDe4lArWD8cybAYkK6UCEsCN0TrpvfH8r+s4108/tqtJGhHB7F4R5j7x8FSz5g
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: telegraf-mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_MQTT_PASSWORD: AgAE8gZLR4tbjgoeWLjuDWRJZVszowo/3yxLkbGWcY3KkUCHrgKobhtoX1hCcATtuORzF/jLgXjksx7aykioLk/maA/AStPJCS1r6CHuxl1dqXDblDHT1ESETwztJyLucQrcIZW7v9fHC5JgraKcRqbtbRA6VQXAv/7zPUMDldNO8LvNWp0x1y1K7exR4/58S5vGvJKDHYH/JTdbP0hy1lwYgq6DADHPYevTxBff3W7I8DKGEppwhpDRFbI7ziMf8nRqXZBSZGYGFjtMzD8ltKO6CO0ZisRgTuP7csHFyU8RE1bfUCDRFsAuuiRQGBxjx0aA6cOSmnnWq/YnP98nD0tCHVPEcB7ieo5TxvWODZXtBE4w/wrlNCeeYf5bS34XpMXJB8rApuYgrBsakjilrV4UDJQIVnOdqSy4+qcxi20+7X/OQm/Zk3CLYaDQR7Y1CzujiKOUiavaMQuuHBoD9lhyOUPfkFg1A0gK4nJfRW3c7+Bpfj8FmxAWSEDBgcW71reHt7y14ZhIooqWB2rcWPoMcZO9ILbVm0Ic4Oz/BnyYP9a9MxOCnmAs38hpFXBFCGmnhKXT470oagsoz9enuNWQwUFT29aTJ1d2/2Hp2l7xZ6pzyicDXHKoTHFFQfmMBMsprPa5fOUPao31wzuxoPceJvDHphwrs5KP8+Xc7Rw4U/2N5WkCIXKmiP55+nLf5RAk8y0wfiQdctbiZ05/WFDCA4eqV7hei4z6Gwmy/NwM+/bTBkJihAhCEZFSZNX8ooWiMwzLv4Y0+X+3O/NkTUGm
  template:
    metadata:
      name: telegraf-mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: knx-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgCPkJscFJiiUMu1VPTJ9vyHEBkRZg8w+4TsfR57z8queV23GG/ZQ2/ZklYBWA2s27tHVzouejZ35dCtdH8c2HjE4i1F9HAvAXDaMwKIK69I5Kv7IFXNIWHnTdkhO0kiakc6SVWECAzIzI7PrT/RNjZLS1/Wu0uiEYrNG0aqkoETiORixOmdrvL7yIQWQ5y4sevUWbQCRjAcWyG0ZCEKyQIkgJFBcNE2m3N6IGgRtqWAKdkWPBR63qjg0/LnN1xFCqpd2XgZxkcotqp1Ec6eGLhr9V7NbacgW3rZQ8wpahFdazfPfVzHT3Fv0dEOpQAkmu51RkVVWkKZ8bc7xqgVAqtS1hYeRgfbwKIb3iv6iWyJUDRLSRO757jea28X7j5XsdOaoumPYWylCrokAihyZNFHKgYR2zrYgYnyhyW8kHeJvdgENzCDsE3rFzl7UG/rZ4/gmoHRoFwfDn5Zo03MdNlHZZEHWNZuE0sjCKeT4r+eX0CdXBrJLCIEkO0xEM4wkc+lWUxIzdc00cMOmDMIryJla8dqbukd6119rEKnkk5RUbFL959LyCDXid43WU6StrRaT9cNqux3Y+cQuH2me5N1BR2Dc2Wd3fAbCY5AupUoGP4AjJXN/9cNZAS2AKoo3ZF6DAO25hYShjKto8Go/FGywe7GCgvuSFhvRUtY/v4k7NOYW6K56mHC756Gy0OrkhvZjQ7fdma/jiClcoC3FwLoSTn34veU2MTCQyp8Q9OXzDaHWVgN+2s0iwcYJBeceLtv5YUfR8bszjjw
  template:
    metadata:
      name: knx-nats-bridge-credentials
      namespace: nats
    type: Opaque
