apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-auth-config
  namespace: nats

spec:
  encryptedData:
    auth.conf: AgBs1uWiMgkGXgWSSN71HrN9fZRFRSyOsUEAkPRYigpXAroJ8nNs8n4DYQfunmNPvH68VJZ1mkdjUkxCHwTslvs2tHEqTRhpX2edyox4ZHTSYZ4Buz2C3rlyaj1eUjJbM3pTQU/hosYEHF9NTCP/WJZ/J6P1irUFrH3qHjNkEHzKEFpgqjdtS1f7aM9RtoSikVtT3qKVvVFes3dB23OvaB8caBNrC5jL4wjMue55XkhyYw2iQuMins6j8rBzkZx1Sgyozr5EL/CL4VGVJGhQLdiQJMI6jrvuMgn5ePMgO+l8EsiTc40dbqT8RXPg41xnhK24C32ZZKJveb926b3IBA7IuOyjSLzlzHMqaA5UXGLZ+b4GZ3zpev8N8lsPgO5Br4DJkKBpSlCcJYFMDoauU9AHGd3+yOPGF+Ur5C3eCxTe9oLPXATBmlr9ySk8H+erT7NQNpWFApu/q7Rb6W+TvGcdyFCYfaI30YwrI38JWHSSVJH2U6F4TXRlNRmfbG4MqZ9gThqHzGnLY0CUPNdPk8hWsR8vlKnGMfMMjj35ov9TYUdmSsghk8+v7XP6MkMwZejYwnMyN2Umz3EPV/M3ixPv4L3k8ppW7eNB0ZCCats8gHK1lXYgjOL906inIFtmLLHyAyUeymJrbfwCTY+AJSoQXGeD8oYOWyh8/L1EtK94xMFxOqV3tXqEG1dzIUw6z4er0r5RY3wwSHjHUjM0H7LXnENwViAr7ijhv3Z1+GH0MMU4D2InTSWA5FTiJeyJzNfNDI9TR/v301VM9luRQIMb8ZOPmI9SSyrtVsFSKrbtp4Um+U7oi/iBpr3TiBmPrrTx2cdEzzPXIj8LI43lSHtsp8HMgls5GFXtQ5SlkkMhCY8h/GBL1WfuAzNhHdo9WncSarNJeibi/8GbJcJIAEWLNJDsnXllY/HieI3Yp0R9FQBZoEtDodCr3iL5H7T1SxFEHNBZzLRB0WI4CcciWi7ID4TD3ajbmUCyLExMtn99Z6EOlKw8keRNs0NLO0EDQkzf5VCUc8Pz15xNq0cUttyKY6zl5RmvdQlmhaUkQKLc5ohcf30V4MVEHee6D7J9vVy27Ju3S2/iItdLKlzdxM1ozORba5Q2C0R3kppGf5rxOw7dlDCv5U6COaLqCmZWl4G+xF57Wm6tl7zg3kXfOb84sNB9d+GTAr1WKH2FI7yQfnmPOPd2ekIZzEuAOWZJ5DZPQY87p3l4a6QnSmnlCADTq0TrQ1wA42NTaeT/45q5PluvMy3P/i6Q1nqv0cx6KAJl5dLdPlpsyFDE/0rkdHt9lUYguFfJVnlBQ4nhrkES7mF7q8N3gIKoqALg7/CcpiVKRT/Htj/SWbwClpC1R3CuO0uV8Dv12FArRQr/nuqdfKj5GyJglEUIfy6sHCwpIVIlgD7zOlOknDE9yZHTTNr8D/5odbaBP53at2M+QetRLVrOCEHcC4rezVbKVnr2THAmc4h42C5oUhCCNx9mykBtfx+R7XDsdEylzhcDM4+A0FVW8o/LHjTDr0tcE8ZPMiKHCHfO9psY3JC0G118cZUWIc+VQhjLwN1ho/xze0RLO3oibcACUVT5SiNoV0qsMmyLS378LinP76R5L8RhNOkCy/WRRGC+XD3KF/0qJkw5MpOmG58Dv1CIrWDgzaa1iVWvQxjjZzKlVaC+SnPLHyq7zW8qgbCPonT3oZznde6O6R+uO7GzZoWeFukXuG+JnEC+tmd4/+fDvrOoVqH8J+S57x14YqaMnm0tD7lgMuHnK1sp3cpaC+rvqu1didx7JiRMpZdXsHL4nQv8wfvv7oU48WqmuWjOO4NvynEMVaj110yxkfpbdgrvD55s0Gd+EC2AOqzFHu0uYV+gsZ998ZeIBp+j2no5p8Z4RiI3
  template:
    metadata:
      name: nats-auth-config
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: solaredge2mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    secrets.yml: AgBZ7Dvd/CYKdPXtPy9jhaaVNun+C62CYRc75CxUnTliM7bIYoPMNZZLveea7oQKQVuuJReMzUXFOTK07dblDme7LSrMMAca313EoEbbDB1Ss2iFbLTY0QFs6o+RzIYOmfXhnyH6yDTEWhmS90VyI1o9kZdqXKPa065FrK1DIc7dYo7VIngYIaQQmmKuYfIe3He3Hv+So6So5CFcZ8jKtlus4nxnZu3H+MOLpTuRny0W2fT47XEq86OYgcUZAsz3+eCTqzRYobc2vjqLDhrRQI8VgGqeYb017FaRpaif4SMKcm0OGERwNcOFYVAggv0jbP0r9J1/ANc9A5/Sf8QQ32m46ui/CdF7gwFTniEGnyCWS3atB5/DS/VFvupVaODf8T/yABBS8EsEWko4MhNgrQl/9akoowcZnpI2uQ5m0z2SFNvmPFUorK19JDMhqju6sk6jYzfVeg7Dg96x/0SVfYvDxhUPsCN8x1eNfz3UCzTK0zvtT4Z5q8qR4Le5SJEiogkJBZasv/XtJ+P4rBGnCITFHboNeKGHyhThrRYWUIocfl0RO7fu8PLZcLPvfDfMVazcrgSIq78xF4LIQ8jhAA2q0j8EJyZ4Kr0bLnQvlIemJxKgahpZRceUBxJmnYp0z0A4zHRic8dZgSJhNrspgKwGhKORueRw4e0vVKm6LyGb6EcqV1PwMLoRf7S0sjrrU4ZYDTiY71fxG2iahSgzRmIgWMAeXh2Lz257pXhy1NMm40ohum+NZqzYoAogPFW7+0mCTUYf3xj67nV7xV8e4QCe9ac5E/nWe4SaaZ6PPWkd6qrC
  template:
    metadata:
      name: solaredge2mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: telegraf-mqtt-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_MQTT_PASSWORD: AgAruEOFeWbANwpAYbDEHS7oumvxOz9KdVsm+ZAjMnpcuz6yBB3njw3nDW+dgbW0/GmRMenx+N7LC6BgzHb2RMZ62uQ2GGwJ33tfjsfxlAoMACAboc0yr0T2I1Tc4ZLMCp2ao8M5qwRURQzKwNuNxMs20PGlxzfGcntZhp3DF1Hf1DYwaehB4GTKcE+FXk99KzWK6z9odM2VByi3jsBRpLAwoIlfqUlybuU4JhRi7WWq4zsIqSWYfbC3BPM6+o5D7oPimzXnFAMXozZZ01kxMmGjDT9rxMSfWN2/WDugMij/tF8VkcWPBfHXBlPoxXazEdribXSXa5B0m2fgEuoRsk7vzVjFFr3oITPmrlw5HsPJOKzLmRDlLkz/JROee1+o3k5Wpoo9L8J2oWfG/TCCGKv4sHc0QQFSTeTAtQN/Vf8wiAM+K05aSehI+gZ0yyXwxcdnCXo4PxDa8fumooY3ITo1/j85hTBABW8i6qZbUUrMhv9XJaES5kEQLopJPLW+jyZh5npyqW3D4u1XhGFkgudr15xl6oibOKgzctes+JGdSv05vZdwLuiHzOF82SDQ16sXXSIaXFlFQFxlSbQw0qXaTW6ZbiTg3l17snoIycD7bvD4LQlC8SuKRfuxDzuFQELApkkbrT5ItyGZghkSybmVpG93sW4DiWk9WMxwayGsXIp+VB3Dvr+SW8PwLvpEKtUN07qZT4oAOqXEb9sFS/yueKriYi5MJJBvsP7JZ2UX7dx2RiuLq0G4Z3ns9kpxliPPLEj1PedTwgotuT5yudaz
  template:
    metadata:
      name: telegraf-mqtt-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redpanda-connect-credentials
  namespace: nats

spec:
  encryptedData:
    NATS_PASSWORD: AgB8XPzd9plnmoJlVa3jOzmzgt1+LZvVPz8bTPv0LWlpCuP9dsZHjW+Qkd0G5+iR/YoppW3BBMxrml4PCW04b1fNEjHWnAixP/8Fh20LcbJf00I2MvMssLhdbvVsHPc5066XTBamZfG5NO7ASVMf3lYvqXpDfipTALozCK/te7V1ZmOqWPfFSwpzpkeJmFeyNQB27dzXiiWnlqUfMHcKwmP5SaqgsQldomzzXGvyJcUYd1wwWAbMZbyxtKE3jcveMiThxvEonFaVZHwy+BUfgKL3d2c+XfRo9rv9mFtGF7lDN5JQdUeESaj8uUK5ym0jrQvkOp17B8S3LT6W8SOl+Zq5O6uUWUEGc4yrYSI/Vd5g/gEwdxhYpX0jLAMDTu+KpV5H70k+6QhobgdLrY7Bvegbf8u8DBtalDOUBWUTMKjAQo6QDs5ELP9a0sn63l+ltxLT2m3nNcVHdluc7hseaZXBNkOgub1rGOH3k7GMaSIhPD9li9IPDYJyJ8NgbusFIKUUkzIQ8rQBEujbJxGAXn/4pqgf5SFJyvweasRoAc0oGYJ6i8AWfaea33mdsyt/kUT4gWEpvq8ht8DEfYreqmgsGVG0dllgZCHGWs/POcoX+Kzei4iRmKHL8PkE8C97bXA6Jv1etQraYcCG4WP/A2Hof+B9p4WNNkv4aYS0tkMuyxS4ozktacoMv7R3wjgElx0kUi+3zrX9b8gfWHpfRkgNK2UQQDE8kiVoeF4Kjeq9TyZ4/HD46pwb5F5kp1zXabNnd0u0qj/td8e3xzSUpcwN
  template:
    metadata:
      name: redpanda-connect-credentials
      namespace: nats
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: knx-nats-bridge-credentials
  namespace: nats

spec:
  encryptedData:
    nkey-seed: AgBff49En+DMxCpUpgahVbFRFkIfHdk7sGJEbROUYHZ+ahM97pw2wUd+MuyJS4El2ioo8yCqY2q3J07k5mqJkDYsEGSU1vEYx8CJ4+XSC5uX+d8rb7aO0NgCV8qBD9W8G3iCcIT+3P62vEotpsMHN5ctOkMO4WBSFOinPKjoc0NPylz8jpsNPlCszkjBIehiO782JEYHPc3F/n7eryL5+5vzeSIgFFsxEHgxsKYV63n5BDFv0hSc53q6dyKJp7MzqCTpPqNtlt4RX1VaV1b4QakO218bpJ1odzLhRdOEUYR5QeByi0uL65f+NvCti2p1YNrIfBtH6fHdKlg+yQ7CuqmnomJT/oclFdFe+yFF5YnRklOGtD1hkjhYXFrZVYrHSCJ0wvzBXVUtkpWK8OJsI2l20wVExedaGuqzflBeZAaJk7Z9gV4RkBrtA/aj0pDpk1DS/lYVsdyz+4pEUoiamCxR+1BRkSCHt6CSkLXCMpJO2pU7lXfMMGMoXuzvrYyktpO9KQGk/r2Wah3hgGchsqJoyP/JgNDv+aESXSiqZziTqdp71TWYpUhyTHnRVsz1GEJFyBR4Soc0WUbxMqIaVNwwj8NsFICotUiQ9m+3FZ4UP9Kyqo9h//ac8daBSMzSMOduD3lCKDjxEkzjWnYR/0UZM373DCVb6w1SL8KDONzXUbmKMIRumhsMfP24BpPUlxhURGJ33yc95l/CGewDS3aAjqcwSBJLj4rRAO6wqUhKFyWnoq2t2Cy2lfVKwjqpzLqk3bsG9A/6H3Ds
  template:
    metadata:
      name: knx-nats-bridge-credentials
      namespace: nats
    type: Opaque
