apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik
resources:
  - ./namespace.yaml
  - ./database.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: authentik
    repo: oci://ghcr.io/goauthentik/helm-charts
    releaseName: authentik
    version: 2026.2.2
    valuesFile: values.yaml
    namespace: authentik
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1

configMapGenerator:
  - name: authentik-blueprint-sources
    files:
      - blueprint-sources.yaml
  - name: authentik-blueprint-argocd
    files:
      - blueprint-argocd.yaml
  - name: authentik-blueprint-homepage
    files:
      - blueprint-homepage.yaml
  - name: authentik-blueprint-forward-auth
    files:
      - blueprint-forward-auth.yaml
  - name: authentik-blueprint-grafana
    files:
      - blueprint-grafana.yaml
  - name: authentik-blueprint-node-red
    files:
      - blueprint-node-red.yaml
  - name: authentik-blueprint-wikijs
    files:
      - blueprint-wikijs.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.app: authentik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
