apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgBNhLbqy3FKUhJlAbYVh8A/DOnOMyuYvwMd59uDAYMXhoZCyRCnXhzn0spl1aug8uo2/IDhyskiQNYHQR57Dtg4Ja69J8GcRZjax5GHrxAisLGPetSBTViPxy0JaAOnF/bEFpPjWlCsR3LSIiKtExdbAFZW/0reNkKkm6O5+59pQMlCDv85+9Ewvq+FCSLoBkdI2+Uh3KWYvkh11LqgTB/WnGJ0z3hKMWH2i+pQA1cI8f4Hc/E9wksXBfxQP96zSECCr2llmbIqoqkZoG9KKTj2je3UEe9ouF88A35xUbF0Z73+G2D7TTzVwcEdU37mfTI3B3UYv5oesVDRqbWQvVFQdQxjk9YZKbjFZZOkM8VZxvKcYRm7gY0ozYc3CZaD1fQT1uALLf+NwFNmvsws45CNR3CWPgAbBWhCXxQN4RhsFuHfoXh8FeJi1pOozXG+/kmbujykl1/CczmqkzpKzE2AwJ7iRR6zT6k1HHhKR2/n+TeOtVG0ucBZ5531hxTaLzV7jYArwG/4Qww1hICsw76Tj5ekM8IfPvlwPBR6au3fkWxoKLwq5AllGO/uFTqlgBjtlHSCvXS7NPfwmdOaaq0kmAN6Nr4RSvOpKMuNtkJkNwgi4v77vc12APYVO3aZPqNbpbWAm8ELXERlt+hbhAwrPxrHebvnWS5DVBxNSi5KMN2xk9fi/pSYcuL1eJ+mpmkSsjiPSIVKS1pZhbnemtKk8QBTaqMDD1RGvfJQjPrHxo0oMdjCllbOkoSQC4XZJto=
    AUTHENTIK_SECRET_KEY: AgAABvIj/V9xtkivs+0M9AUjTAZwFtIc8Wkm5mXttVs9BRR7pE9yByuuWzHQ9l/M8MavB9IxkVQs1WWXolNdFEggqCrk5dmPwD1L62QdWdwc/MQsjKQ/UvxtWCxwb/563qAOGRARo2hjgzrLXvLKzy8bHB5M/RLrsqldn8KYcDHCkGmnmNlEJX6UKKbB3Uesjr72jKeCSmpNBABdYJBnDjBohoSY2N59xhm0DbjlXhMcBQiSGm3x3eFTKO76U0YI2Hz12nwP5nm0ewV2n1wF5+siy8OJxN+YJ52e7wqRhmCxK1VxsdTr065YQw6/Z0VEUH/0pS+HMDh62BtB78y6RtKcGX/oaI1rP3z0XF7Z+FVEi31kMZdVeEm2B+8/FB8fad9aUorwmue61ygXp5RO9tIEpfa7Acx+cKL7fRd5J4PFmMOSmFDcm16NxJa9HNmte3P6RiXXbnKG1eFVKHFbKr7PeQ/lTdKLueuYxpLX/MoLH2AZ0sTrVKq9L3IiBYK0595iULOZhkEaJKWOcxQmrRS73Li0rk8U2mlg5o4Hc53r+X4vICZRmEg7RXQNeHUeZDyXM4lP3eyo1OCBNlN+E4oUuF8Rq75WjzkzL/yo5+vDAUOri1QRzaIbKJCxBu6Ll5GMSghRU3KiUkPX7akRVS2YGBGkgXQELT1/mP3JHEuiUxuhwUGs5hEAGemc6+W8UbTqxI2fO7Qpcq0c4uafZ0967miSfDgARu29xGDFQqLaW530Of91Grx6ptDKH2Y0mVo=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-homepage-token
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgBVs5gES3h1DdR/3f+F5UGwEJ+AIuy89qx7qn6vJwQHZwAIc7hYrWf5zANpQRNKeBRThEsnEMmeB4pP7Kr5fd99GUEZy2oe1mJE0XPQlTNsuRjU9LfifzOJcywEdPKsZSy6toE+vY0rv6MCDRrNXV0/mOnvZVP5OBJv7uO0ybNzTZpmXr+ZwKJIT7iCgJsrn+Rouknf/+ehYeDBNQh1k1TNbDTPA5XuxoP/F/qDy1/6vpNNZq2PdjOzTC4LdNXMDo/7wb+qlHp78eD88GSXKAtitrdfCTTUIOnHE0GBS0+SU/BrMOy5j02zV0lmVGTFxQsMuA0mYdi9YsIvTXW92QIZNjzAJQoN6FQndQpeJXRfCGqxAxgqSbJfExviqDTXVXPi/19XdXyRVWo+AiylEafxU6OgPfvir5ehW4EXBX3P26K9teLpVNlfyFwaz79nrNllaeEnzEBEshV7RXzIcGXwUgqLTpxOLu6ymu6eS74oMWnwJGgLsZ8g9BF7O435iVBM9aog+hUn8IkrmkRnSuxAvocRFuxss62Nmg2nE0LYcvwC0CSnVixXu1QeiKxCtkIben+ek5/BaqzPVoZ1Whw7RrVmT5Mp01l5HkVTKyss1j7Hz6t1zkGSNw1ny8JAdg3Qv8PdHokh1ZoGAvP+AA7bo9M3P4fGQRT0ccYhGh9PwIaCsKu4CpQ9+e5butz9BjhSIiY0P2xycv/y8fQf8xKXcV6NJbhpAYbxVulCQPo87FDsPmCzt/dzM4MVZUe3S3agitfO0bwmsbHkBgFAoipW
  template:
    metadata:
      name: authentik-homepage-token
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgASF2dldr49orsVTjPvsMfu/W44YW32qFdQT0ab7ZjpdhUZUfikU9+O3i/uwO7RV2xI9gfj3KxU1iKBphkkeUsCS2Wi4/hkqtwyzkpnUgYhWas0MJfPXtX38G+yrttR4yM2tpiXKZDD7tpaNpE1eOsHZaOr8KP3I3x0i8hNe/6HFxaW+m812b0VyOx8giuV/AFGiOcboDG6aY5CCKn3fV8T3wrQQKFXqINOhYL0s1CHRKnJHIWhVrOfos2Qy14xGlu8R76cUlr+aTOjnciEbQrJp6SubxZ7aJdekAGcz/1OjlGsdumms0KMxX5WYgstS4tjs5Rr/vs/sHaRnJYFSYcPl1yDLt7VO3uzruxzb/w+uziWrL8wTj/sBV0cMectLowi7GjwFNI8OYswoCdTgRoi/SpR7vaByJoctAak+aUIShUlkc6LHz7uMrKQoVL3/eZ+JMJnB7wcTrR3dvpt8AhBv7Pcb1e5sRV3xKnobMeRubbtUpZeWLhdGQibfpLHOynCBmO+urMImQVvgNSof/+STDDp/x/xt//BHNzamRTIMGgFxy7/11WfTTJVYLq/iQKSwu9mwIK2mkTd7ks33S9GoBNs8D4cQ/Bf6cWic1PeBNIead/gADxjYpjjOQOAAUYqACM4KfqOlNcs6h06Jw94/eAzXaVECq0d/twu/V50xoHJhl9Iyv7RvjKq+OWdtPftPiezg4GCe9RedmMVB/4PRvZfUXF2I9eYykBfSe3M44OWCvM=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgA4DauHU0uTicKn9vWb1ak4T1odJ0rxIU2F9MHvbZUWFpjIRy1g0xgFStLhSqmnrPZph68+nEoSC884Bf3QLKcXbEzugBCIS0ASlczde+FJbIz3Nf7y9p26+KApGa2PFsFjyeYSUgitQUz1hoHeJvyOIHozCE6tT9VJCdX70xoj4jNW7eqMK74pcxLjeehmZ/5PXPSa3012mgF27NahVvJlzcPVqbaHrBpRQ3u4yhKpzRZAZOcfB7Biifs2jqR9gjM2bRF382NTnLdjslBNfjBMvdOHK8rWnuxcW831Kkdx8TaixT5nclk8PBW9GVt6Zcc40k+Bi4/1KVvY6eAWxfZS/toZTPxMoCv2efOvn7mQ39AuRPewavI6AW8APrX0H14HbqJ1EOqr+trlHU75Zp+QY187fITQNwM90GqcRlo265gJhHVMr1nKea0a4gXYJW2c2ns8pX3w4eMYqxwq7ROWFkg0nrNEo+ti3F/3Hyjd9w2teXSN7Fa2TPH3vd6FCnnWNEZEYcRUirlQMwsb2f5jXVq+zIKgUvSTEA+4hgm3YRWuBewRODeaM8BBjXsCe8k58xdkhBC1C2e9KsTmgQxviMMEQOlX4aL2FtRcN8YrVN6sn3h0kLNFdrNsT92ukmHSCF/VD0QsSYcyxsN4zwrVK8qQ/UM865hGRRu/xd1DtVLDSAyRkCkCQ1bAZ6IrTMiGaFSXcbYiVDM5WYnmviVzwcwhUfPG8VUH3KghtjbbjzsUR8K9KnL9b6iX6Q+t81E2F2nfVUzwMGYIWg/MDEoS
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    NODE_RED_OIDC_CLIENT_SECRET: AgA0XZw+kXbRe3iV1AiQGuCpg7PTojzKNArqyHXV8h35f1KrcCgSRzdgkP+3hU+EBk2FXp4G4j3v4vsUto3g7tTUcUP4c4pXCkv1udLI55Ik1JLB3K85roQUpO/L6D0edNgPrruRvU+xT31Byowky0WNgK6KJsuuIh+QUiOClboPBkqtFnWmv2rzu8OUrgxpsOI97z0Qb9Uw7INgmqnG4ujpW1aua/cqytM2HOGrw7krau/QAKUFR5t23ZedvvKsOFLm5URov12Kl97P3HzYSUZgv4QaoOmCLJA+XY5Hz5tL3aLkWCZcq8KywiaNuXuYk4iG7XVLDfYwJcKeXHngUOJpkMHwHZbS4s0khkR/40WG1i10h7i0JzDxUTorsCAEhCNlVs179sVJB21r6vdVNNHF1uoEipPaAPyroMmBETVoCKFJ7pFaFHqdkWOo1dAuEEPoDyh7WYyk3DbuCRd6DG89TSWiPEbDGyxy7CAala08Jbjo0lGEYb5kfcyOvJdtNOQjMAvGseySV/YYfDd9/WwcYq/n1o2U5rgB5ytLTp5IUu2yOlnNbdILP62U0aC2nvjQRCXrJjt1Sm6pfjeNz0fzwo9/7XbuMLoAhRuAk0wfIqp+RT4VuBC2F/lm9n/bSCiGHs51/gk92eE/fmT0dFotTcSFYX0Ej0HWTrgp43+B0QXhFPcxg0JmfBUZI28k8HAU+tkdJJedS1ygtixiTQkNNZCV4HU8t/QCs8JFeB6KLPLoWe1Q25PQaKJqxb8HZZUDbtQaa4ty2poX7sLcXC+p
  template:
    metadata:
      name: node-red-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: wikijs-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    WIKIJS_OIDC_CLIENT_SECRET: AgBJA3yjq8+NPrLRjy2oua2K9QF0tqUE3HUM2Y+m3LR7LdBl5cZE5a3irLx1pF1wD23Ugpy7UWEnF5NHbOjoGuuOAQw/nlNRIlnhPnirnwYq1+S1Vn9SWUl8IQ8WlXThkV084utbZCD5tldE0UMmEM/tEP3KYZftS5s0QoBYot/71blMeiFAZ4bZVR825HKrZ5YVWreZCMIW96lEfhlkjLS6qmTPjhCEZWVsAPHsdipgjLjAKwbeV0oVZS1D19usJ4MHPdOtaxL8NRYkVmntV77Sth3nExsiDKgRqYzyLxaKf5C1DdbUFoqcUsbOO4hhUfXBHqaWTgV4+NRU/OYfPd7tLW7dlbRVWfNBGITvb48FIgE9n7hS6yoKJjMK5TVXFD4XATFuCVjMsWI/IYjPXidP2cqoRwgC8MxOWDgn/C+RsuO9lzh4yOf/wpQ7am4yumjhpmr5KGoAxyRHfdXw6v7Gyyfdma6JGCUNtxxMWPpygqGFzbEpBNclK7XMo+zB1x0eY+np8pTpx7dHsvV65bm95pi/m/vHx7JDCWSeKwpNCchW8aETB0M/XiNC2wV2cxvnywl+uvQPjw30UcoF2UjXa73ee2LlFU/Z2U8ekmFzV8EBFqrTRgdCmM1XVO9uL2u+481l0GagfnZHuS3Q33zjb/lmnJm15zURKj6DmRSEqV1T9gkzGlwZZ0hxv40imKCf2RPi3uAte7A4Blnnv/GoEe5IVZi1Tn6pjGrjxTZ6beNUc868TyiXkmQLmU0HAUMWpcq1jf3hFYTYesMyGy77
  template:
    metadata:
      name: wikijs-oidc-secret
      namespace: authentik
    type: Opaque
