apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgB++zIprNKdGWnWg/PuoWpaJCSX/OyML450zEHUaZXLeuOnhxBfBy9guqk8Kf3mtcrn9rWUz4KM8xNIkHfh4wqCHqPdfVChKi2wSc7+/Fxy8F6JW0rnhcEv0CM7YIUDM5e4RWlgtsvX5QKo6krekEqH1RBnITsDgGdg0y/yPMuuCf0DgU3Bt6B66tUrKAWhJxaYyMqs32Ny4TYC9NiuBjOUJSNwA+06SEQM1VJDMD/jSJB/leJ7cTbvEFfJRFIkWKyLGLoSV37DJmpqWoDaIBD5qXSP+GG2r3xVqfkfvcXDcZk0gNEG3d/0CyceAiVpTV8GegmNp0u/vu1dNOCLss+IY2qmAuNFH2X9FjLzd4s5FaZVFAOotMDNlV1NJQyP64LA0S+pSp0vcB6ptUYsAy8v028ffq1JoRJymmhsCXipkVIW2fQLKzt6po20VHz7oNvOeGgxH0pdOxi1Aszp2Voqp4N389nHHlSnqDCcvpp8FGVLXX/BPcRmyY7OERwneXi7td5SGL6FHbE1XUxQhh/L4s6j5lfcAe8IfgM+X4Q0iiknkkIjaYLUBKOzzSKeqFSwsgUxBp5e2nbpINbnmAlLmrLhCnLAnKO1H+BlrM3A4f+MyrERe+Ac0Sg6z1BN+9J9pMjCRipVQrl9crX+YEB4m04/YBvVSUxVZzojZZbinGpoLvMHk52Oi0ZQGanyGAMcVOt616/2Eby4ZlyJhoK3Yt5vr+MPCmmFpEanqZQfnmMNCWipmuI0L7wNc89Ojcs=
    AUTHENTIK_SECRET_KEY: AgA6OtGsqHzO+UjhfnxxCgq4BgBrJsj9Uf/30j5oNZ+jVZerJ6dQq1uaQmybmP+pigTwHwEOrNi1vHvYsR0W1roUDJkE4HyaxYpooggMpfOG6woobdNJChs2yAEITmwtZCKG6ybtzJN3NV+b/lKmPFtgUc2MRXZ/kBRBrNay7ZY9PV5oDk+2GXJBhY90AD6Le5x4ERAUnPW8HaZ5HAJWJz6xL2MrIg0Ld/v/b7LG4Q5fDMF31bpuyQU5WOAw2MLIhfChutnRePfzjoe8ZQnCBHadGvCv1SEKCVPuwpYmowwfnzD/CzkvxYaqOf2pzQKQoAqGkhRHnejSbRSZ6xCxHjjSjRskwTWJ1bBPLuWp+KAbuzOJQqTI8CtLPJHpMY1101SWfAeHUEPM0+At2/sTdUXI9QzwJf15l+7twzpcfus4ByMSql643AkUAZsup5b1Vbglay+qtRK3SDewco5a3g8Avf8E4N8ux3ZoDX9Nry5E/czOJvFdvPbx584E0+rbfyA8BCeW9MSxoklyTDeLuKfdtvjdgavZcS48T9wmQ3na5b/Pumij4EB2bwT/eOwa+217DM+VBYAGu0Y2XtPGOQ8AHtzEEsFaYQQDOR4A3Ujpiv6QYM4Ewax5nkjCOBdtLawgvN+fBInaMH9qmL9hqEv+5wXPHWtUUKKZjuSTz7DDiv25tNCE73zQgQZhYRDXpVVojCHqG98mRkU7OlmdiDEduTQM4B7oorsuFK3U24dDpXGYtz/VAGoCseU8Y6TESaI=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-homepage-token
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgCVgcxlmhZbJ1VdrOTufmmDDaO6Fw9ZV6LWamHcNxGMIx939gCZI690V4l8hocemUN7PV4O/MVnsAIChPoDRhD2qllR0DZ6DZuopqSYbbtclSfG1P4V10TCti3OltZ92ehnQA82kDFgwb5Cc54Cw5C6zyuOEwIMcChnbdv+CyrklK3ZQusbhFToKa4Qx+Ao8/4pcQLehhKAluqmOZOLGeIXrshTLdwuVBgQYAyxx1tMv83a4apBn1rnSKF2bg+sbx5sVKPkc53QVJzQ403CBTkUlW1bj37ETyMv2FF26saXox3gfCOCfApVkE1/XSPbTl6bpNvNt/3/1jP3ZnjrBgqPDBWazWKEmCrqDBBbHMD7U1ts9/Ygd5NvCDtwh4b3xfxiG9wFcjtTzjWu9PI4/PSmfJeNCd/s/DDW/rLCTof+fbGF95wEc3zig+DlcUXM3qsfKTcO4PJi1wfRixzpVYkF/mFsccH/jDtGZNzYzH94Lw4hi1oadv2YEQXA2qkfgUN1MiVro9+d4hC0W20pNpP2yS+Tz6lM9ssUF/EZXNjoueSkShtYbR0Vb9A5NLFry1QZOXRhyPii0mX0ivk/KM66sHvmRZwU4p/tBx8cNy3/Jc48WVl15NyxdryujvKXCyV0VkSpKFDHYmglUwFqF7fIyrkIp/r21RrZtUevj+jAAGNHeDWwQXniJF6HYkh735WkWq0QtoA4pIfUkk8A75PoIZ2X1kfooKYRun0B1Y88Yg3YaV+2Fqk+1qaNX2aqFRkTCE0jLqamDu6J7e5kzRc9
  template:
    metadata:
      name: authentik-homepage-token
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgCS6zHpvFrsJbIGlqp21q0Gxb9vjrzgeoCi2EhMzb6bf15v/7O9XXY5avhGthBnZB9rrMziXypgAjnkzuebmyhLpjYOrFtjQllJ2Opn6HPVJt99tQnNTASEhDWgQDDzj8DgWV5Va3QfuyyGpROnssvi5BpZHAxsu17wDIT3wJMS6i8w4u0+fLi+BgxQanX5YVMe4uxX4zXRB7lQpYXFriFUwCOR9rhVDIbZ5orCTQhx2B0KkiOMaHfCkF4KUzC7BkcAD9ojxqg/Xs5Bh8t8SP7ZdDnOP2fODGtsTuGBZkyTDrEd2eXgyyxQwzkCBKDzxjTYqVRA+W2/HBKrM/FWdRcSNv9g1prTdp8Cs/Hteg9ESxrRHPUrf+mumxqF356eH2xOhk1TGchrT1ZZ8Q6NYY19NS7wny/y2H0ufQ8T+NcrjQK0VGgnhctNnfkAhiAzNplAkU6zprJVwAEDjRynd2EkDRtEU3fVpHIleWuQM23k2hHu0o/UPyap0m8vtuvCYbHbRfR5omQhtJyeNyWWULS92bYn+8e2a8jueuVlLZgE5VH80zwSGnb4myfmY7prdHufuQZ/gyBDNsqnEFpUc+XymMEoQvZRsZCifBfeG+1skl2qAOd1Z9RgMcTIMgMshxwexlmJfJ/4C7hKkeMuC2FIfcERWUqNZqCskm06TmcM37elLWsd/IpJYI4bbydWiTzGlwq2yJQn+AXFRe1ZaWeyK+CTYIToKpRqa3OTXP0R1EVhwio=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    GRAFANA_OIDC_CLIENT_SECRET: AgCJVgn0l0dujBqlyqb7ELVZAMZ80vacB2XMU4DUuFK5Q3KFUKQuI8Vu+7o2DOKJIcF1f6RprKyhKhXhzJuCv8T2TyunUTJdQoC5JAlwTuIU0En35zUKVhBugSnJGvksCreA5EicVmHJQufA+gPb/cxvMptQ3xhTog2N0f+YHeF5gY87hiCrBaH+BtjkfvoX76meohd0JlZXj9wTU5xZ1yaEb16bOmA1s7o4Xym+f4uF+N4QbViMxmPvEOU18LbezduFE0KkP8CxVXI+E/s7KpN+EN1JvG8uQbHMNNf+CNKt0j1/vMwdh9o4CX6Oy8UMqZjWmIq/dXJbprplfoS2SMeb4jfO4qDWUNhBUkcnbk93vfX2dCDfbQ/p8OC0sXbNJgLkvFOaAeqvQDoJw2/G6BOLrVTa9THr+RH6D5Xmin8PDQxpyUuGIqjdGdcuCr8RSzRKYYMY3HchxjN4T5EjIICXkkAxf2tGHByV1ONamWDFQyP//eAO3m/eydwjP9yuYUIXHF5aXjGw5M27ug07XXkyW4aVgU0PVTAN8mONcLgDuJnCb1BwQZ2y6wmSsKtwjFwUeGqFGZsveekUl46+MPp43Ki+Wbz9I8693CTbEeDD29TG/5V6lWVX1Gz60P6xpB/8lJHvBqkUKpHc9DDhdFlB749lYj1wE6mdcGuFF/H3HIwmyawSB2LRF4vrEhftFcL1qRf0if1cNzTZJAeRVh4V5pW6VLgP588kw8bGg01L59B5DJgeIaihGPXjUSZOguDXMpvypn4ycYX1shfLQus/
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    NODE_RED_OIDC_CLIENT_SECRET: AgBrSh6B5hBFKOXH4zc79Gin2Yi269FEAWK+D62+0BKb0ZYWQfUgOfvpynw1+tWn3zE8+YNhPjwQ9B2FfrZXP3JjMAB6FI8AoOo0tKZOIIQUXWc469CuE3iEABRlgqg6oZMqvywD5ap9Yh/sJyHswmBvhhqixybFWHs7GquggefWhXaM46BcDJkUk6zUuBmq/pkBm7YdyOCfkCqA7yB7zZ7/DcYQ3ykdsyGjUTFxpKYg3IX4uKl0MAaWhZur1rko85lFJhL8MLF1Kb6IoGZiyVu0YDn20kDTXqU7t70+WpAq5G4tPMbMl+cO7839dthN1dGnZUQduilBodi+w/JPPmVm/RtVVKmX7HmwkVVvs9xT6hzO5vLF8mlFndFYHfxPsRPw2VWtAS5kYu4djvsdZnYSk3D1nsOijgjEJh7LwLvsWBHHvIOPb7/ZEbtg1ma6PQGLMI0gEVYtWL4HUDAzhyn4sdhY/+YUO3pruC1AoFPpA6n2ZHGYvgntO2YBFBDpgkKQuUVhuFeUTfdWCMRZCYPaoK6GexHowA+gVSr4AAZ35zgA13JXzHip8cXukvA4HJUOXzr+JswrdwILcZq74+gZ4j7LKXfeEhnYe23X7RBMZqOgE6cCZkHy46evlUTNvrwDgHmQ2mbwbxV+8I/SRwmKXV/bU8jkGLdM5yZzfztM5pWjoYzUqYUd1xzCQ5MYkliDUYpDSkcYgdUyX8K/KqLmZgJLVh4lLv/03rk7Mlcs7C3BSXszkKU7Tj97gBbwmt3L3Vtot+K+gs6R4BAt/5Pd
  template:
    metadata:
      name: node-red-oidc-secret
      namespace: authentik
    type: Opaque
