apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik

spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgAHKeEwKWmGh4UFC0HzlIzEAH9m4QJb+TSanB0xwQNYtYhRJ3TUAc8tfCvxb/8UXNL2n41188YQHxs/0GFPbHkj6Ax3IGa4jBWK4ZyCT8U9zXMwiqL6l4hAR8u552yd/EOocjU9KoAa/2akda6UyUkc+7TtHCZqOYbEc9eHqJsLvNGeGTsROshbunDuuVRBUARMDlB8NFIkjg0e7IVUH7rONMGtAUFNh8Q1Y0O273ngmE3S/2OGWmudEs1+HZ4+eAI76l+PiZ1/yGg/J387dR8EZ76myM0H/KTZmgL6N1YTQLsJFAHw6fxWV79tx8wlHZSRTmpzMGoNU4ySfy2MF3xEM1fSMjagiET+lt4ywCXYMK7CeUQ9B+tCf466XESFjMOWjq5dh6OwKSAHnPPaA9e7q9HPC3oXq3ECDf0a+p17SJsoMoEIvsnkY2hFWmUpMpFvyRNb3OF0TS0zyu8qBTV4fZGgpD1U1IL+z3/ITc5mWvISPOwZKiHVIo0hFDARjReb8P7wuwGoylre8DLLhP/rFW4lmLi+5moyhnOte/IHHJyqbv3M3jsX6hKLJbzPWBMHCfgsSkc7lltwRHSebrG3XarZBDD9Z+eNRC87cjFmejIIkYifTKvjR5PH8wxl9jDRB1A9ORcZ4iAlY4hv1agkhHC+YtqihHJnNv0bvuDg+Z6VmJqBOZGIYDrVE6Hx8Ow9VKmOIVhvy4noXmkTonNkiFHJ9gC/kiNpA9CPrX01ZNYAaqDN4p+ssWybboq6opc=
    AUTHENTIK_HOMEPAGE_API_TOKEN: AgCEK6fEHlVe+V9qjb2yK2fl+d2GYDnCi4ika62WDGEFKfDmh52Mwn1SkRrRrvOp6ufLbD7o/nBc3QK8luEtXF81MyKGEqY5+ZqRJAUrsbJYuAz5o54VilL8b+pMylLtZz4VWL4lgTXau0+4eUzjCMOxVYYsL7qohltaZC7AtWXnYA/a2jn/BslfpsxJGz1BsiZdwm1VqdPlnPvr7lKCCCGfgUIddovOjs3utbPsaQlXoKObGWRFAyBKQkc7XHa7ZVcMYHlAwE+JaM+M+a4sbIDDyUODk1ngtK2yX5Gw9gepfkcX8vwwa39gRPyy6VuDoe83skTF5/89fkWwrknWEMesFC4Rdkr5NE69icbppe9+uDFZbEBdeOnB6DjLI6zjjz/wIkOGGCccoTv6ZkPWSaTS2m9Oe94jlX+Omoug2hQ7/3IV7v/jSQjVa21CRBFPfPjpc9W8HYxVpfld/n45EmxSlYrM+ktTrhrgn1Tt8zy/DuqY26D6hEevtFOUNpN1kLrPzbf8/LUo0f4vWzq7mxrDO/VuyQQWYASwolb7pEqW0wI4zqfQ6CugI4EE3GmEYJusjKeJuXnFjfYYtGielxJTAyKXpe+mSmsjGy0RyjeyxyNGUYJfnmjH64Je3PeK4vogfDXDXcErJrHCtBz6JS9q4Ah2XvPValtGH9pojWNcAE37hxsXOL1I9V67g9AWdyk3oYkjmS37rTzFGk6BT2RRommjouvDVGoXEmSJ376G822uT0JFKmtkfS1faHIC5lKuW7LtGqhfsrDSislEPduU
    AUTHENTIK_SECRET_KEY: AgBkEtPvqisqxVL/M0XjLAg3Gsubn+rAknqP13gCL0TCfcU8uNTmQGTT2U/5HKIxQleqm6Oa67HStME9nH/hmQFqGyxVD75BxrfcGnMIyD+tvuxuLe8ZUo4BCGJafAAgec+N46UAPMI9GO0fW8sLfnY0KxXFeJOkqJyNuU4R+5drGCCdr3u3WE0ObDWPqU74sHt3LV4lmzgrz+8sMzkr+ydskgkN5GS/tR5CnRZaDXYorcp7X5LpGnKwnhMP83fTGdKboXjWymt5l1dw7aK7tbhuDiNj2nel+7BzjjY43OI2tJMzY+iGagQtdeT2FMAt/XlFL3f2dDfBt+Q7l+nHWcrm00CaUEKeBkAZqcUg4jlNS6jFEN0oXpxL/Rhw/SW88siyeNiEJZBt/4AiGB66zG1wexyyg79IpzVRRoaTVYuVIwBweGddzg0qoGslYEOFOS4c7Ln/RqYtQMSjdv6kpv1K3m1/Iy3zq4VwoxbrTazdUaXZNRraRJr/UuYZzhdHwVUMeCMIb3FA/CKmGkFZKjNZBoI869IbvPBZ97r/8Dpq5blMP9BpPU+ykOaq4yPO5QZJWYFJpyWjET+mtkaAfuYqgZIBFHJ59WfvTwrmBLc5eEubN/7pCMuMOebhzUJmBlPhUpzdtxKjbqXw429cjNJXjqC/idpEhwQmBNppWySfNPmYaJlkwxX3ZmLPJlbu2MBRnBQhbbTtjfI6Q3QFTXsjKObDH+wG8mNXLay5Jgt82uSS2DW5OtT45rcJzrRikuQ=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: argocd-oidc-secret
  namespace: authentik

spec:
  encryptedData:
    oidc.authentik.clientSecret: AgA/0u0XY2V58Ev8MvEgyAJfjDTqGJeil0aW3ZWagxCoZf2735Lal32KzKJvRtTBCqIHUbDRkBLkgNhYqrIH9DjfRnJOfjvYu23N7VZMcZgJEw30e1C8aKG/OwDX9e2P+ZFoaKD148b5pDLXl8hWdDZ700vg+znvlYH2LyrymPCIdsVXteZvNMmks5AZMtsPUNxxzVcrECDE3h0LBJ0drBb92KwawT4aU089vcglozqln8j6UWhkqnEWJh5IkK9wIBREvmh4XQ5x4v59NO+ceXeMhzVg9b9qerg4G3d90fDYLPuqbdE7DPk70Lg7TrRRzV3UZXJIIDh3SLtCqA8pTv2MfMCPUdA2MObE23lfhRtxpT7YnXkQ/75FG2HfdUNzIr3lzi3hF+Ey6z1lNo3gotZTSmN7TMmhVywQ75XQXaHXADMTDr5UZEcOUd9ubTUeUyYODmLp+hG+u++RIBhg0Rws7RlQv4JQ6dJ+rij9SeSvXqxwh1C/zWd3zHE6EWYlOO0qebToHi7nro0OF8FmrAtbDIr3RMN8cHN7ppmRgARZQz8BKZaS0rPKterJch4ZqIPGxNlM13exFgH7jz+3H+YMR14EvELEfKlrfLNY7ZRv+vAIBhUpGDrwJCLBa0yLX/Q7zuOvWQ32gnSRdPmeinXAwF9jmn9zJBlQJoIuCzt+uFzl8VtXjHRPc8/bJuF/DhX3JOPXA4acriLk8Hp+24XadR5CPdD1drMc4/vQxlBUQeUatOw=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: authentik
    type: Opaque
