apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mosquitto-data
  namespace: mosquitto

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: PLACEHOLDER

---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: mosquitto-config
  namespace: mosquitto

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: PLACEHOLDER
