apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: alertmanager-pushover-tokens
  namespace: prometheus

spec:
  encryptedData:
    token: AgCRuHRNqtvJvs3//4BVM1hjIAdFQcIzCWcNO4x083aNvrU3USw1hmyC6YHdt47TEjnsQVvYAwgxVD1/tRYc+yiEDRTmjNWiXCmVQ2NJ+girpQCu3P8FNWTjOUUxL0iqHnYTHz4G/VEVA8TmOvKeD/efEvP/zQQJChsnleQGKsgS/QI0Pom//VwmS2TS7JmmTbm0WQczYsgHo/z07kK+iiblrGL8NPWptvf1eRT/R9WBWYlvNBd1L/IMSXpIgCG8Y82eO6TpYp61EF8e25bVaS2b9J+sO3ttpdWAbhBGQ/QnwH91Dc5byF8criJ8GJHb0FRqoI/3eeIoGhdNUnONOiKrpcBRj5BGEP8Hs2lnAszJRzw1FgV6lV3bZmbeDjfNyq6zddQYB0B3MMc/qyMg+NxPDs7juwgEWY1KXSaoTgwnw3iFyoORUB1OXzFO/jo2CnEBwugJtuj/evBYBQ5lDwlRbqPsOCyyV50y0ZMWRx4/Hd3hcO9OmnhUalixQxIHEHJTXR2u+t9+n0j55+vEop6JaHcnzrJvnVL7tQM0L4rZIiVgwg3Nz9MW4+Q4tRe1LmUHbSR6cMn0/jhl++Zk9dCYWR7vnxCtndylFrdyXxnBs7gTwVfA1uq8Wx52wW5eQ9JqIsje7HAfyYH+yx2yeD8AvlRnY+uTUUKXWqhHTXDjKWbBdOESCp+NjB/v25rXxX3tPxyrcf31QIzAi4Mzc1dz5YYtSp49yEJSH2OGawc=
    user_key: AgBTAGt10vINhCajKmyBBppW64MrSDeniw3JperkL/QlEzBlz0H8IRtbeH80yjXCwt2+Ygh13AipJvd+DxzSlM7x1y1HzsTxjt9N+1lNm2FZKwOet2uKLUqEK1K76ovmWtAJsjETokXQD+fz+v8vIDoPYIWvL3BmVOHg/nOL5WBGs+MNVjl1c312pJ671FyC82QScxeF7YYS710MEvfTkJkcWPhoiATTXrAszkdNhWzrl43VOkvde6ZEc0tLFwAYs8oYN9UZitgtUtT2yUrZOCP8t6YVtD7ahDR5TeeOHIaZwU3HBiwOw/VBbUdns9/HQvOVJrSbONOofY/NhTE+odoNXQZ1BBJTntNK7Ge8M3eYC7AUuZhEwV8JKI5lKbB7CPw/7Vn5k3L8GV2bTY6snUt5cpw+QaQFYSh480RTL7loLW4AElSUkFuubyQrCw2pwRiDZ7QF+QYKl8jac90nVDsGOD+QVt4NwNgw7qlOiwQIXrEojZ48VFWZ42egg29POWwQ2y2X1YVC361SPSg8w10JqOu6KDvYTNadtEjw8EQX3gmhbglt9vA4aVKoBXBN3+Ue5vU2xnDNGLGE2JoDasS1Cf0RQCRMByZhf4cl0Vbz/TWVw7JpDQsDkTurfGD9kygL/aiXEeW/A0yEpEcRAGGGwu1AQIziaa790Maxl5lRrJ0N/RY451ruQqwWmPaxNJ34ZnEOxfVXwcAcNSFV4zgOCwY2I1G9DIBgJCOJWgY=
  template:
    metadata:
      name: alertmanager-pushover-tokens
      namespace: prometheus
    type: Opaque
