apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: alertmanager-pushover-tokens
  namespace: prometheus

spec:
  encryptedData:
    token: AgBAJYrInbonnkQ22+nQWnCHg5fx1YJSHBq/DB9Qewm5EeJXKocdjAiV+NUJBsuERNuV2Kvh9JorCm7a57ePfhRf8wDpUNyHmdRiDzV+e/ksCDIIxI/fLnTgoA3VxULD/bnLtzuHjBHGNmB266Vc/1IKkkfYNmqV9vEdof/p20Nk+CLr4WFCq4uYPAa/3OCF9RPx435b73OI4oJJWiXvjG+3YJIO9GKaqYwP/Sxq4N7jFlj9u+M8xiFW3BPAP5elLlSLTG9xxvs7u0dX+WIl2MVHZvYFzqhscqhF4mjToEQHItL4VCrCNYlVNOkvExFzB0YbcyQDv+CJrlZq/hEJjkcExqokEBFloQp1xmgj2waJXy9bpBr62bq2/ub3mOZG7/OB0RCHnZS4EiHMxC2kLVwdPHpiAin2lo6L2zRMmdn2jEdddH5kLn8JtsudUPoR/xGOhxn23SFtFYF6NB9XKucoicpNDjac6ndWqU4y4t+UhD5uWHehH51uLFkFlpirhsgH768VvDAZBkCc8Pj/LeVfWz/hydnhEAlY1obGZT1YWxIpep9aCE4XjUimL9Q8tL1sGsYcXA5P/6r+7HYwqjNrftrqxTXIeVQwZgafiXj+g9V1sSMz8kjGkOoLbCzuCj+0dSUbJxbjRbeO81IVUIeu96lHPnhErbf9ax9ncYUE5crpsqi+JHNPL2ac91REE36QB5eAKVz+IezX3In5/GkOaJMhuAeJ3i28qrYlyik=
    user_key: AgBUHfQDgognTaCWHX0ArFF+G8To4YJUlnFd7Z1mdoglsZUK+h0gtpCi9q8/6cgHchqaMGc//+r6sIWb9amvdpGKTqNhsy671LZF0qaHZ/aYoWNqSCN2isAIJNeSSSB6xhrtFWs55QtJnQb2iXtNGW/XdYRiawP5yXlWuCh51xR+6J2fJAkr6MZ9uKRijKJSHf4WWLouWNdJk+Y21iPbvC1z/N5TuQvGWHTs2jwUGCGgZk6e21IBrxIv9Zn3UjWCl/QiwvX+Qrk8PblEjjKPaiFAp3cuVgD3qXk7gRon+FEgGQn5Bny7qapPF+a8hetvTdINrDWp0Oz3pQKFOMXSMQghEzoX9TJHh4k335XX54sXXhi0vENdi3+23miAR95A5A+rwbepvKrkwEItBhIBD/E9ouMfHUYFN8J0JgmbVFt2yF5UDyLrWFh9j9UCQDMzUJ1l2JWIT6Rr4P20ZY8Wu+yL4JaQCJWtv5OwADuyfeFJQGdMwSBZg3SfG9z9FgJ7wwIO7+xN6VcaxC8DFjbXCtnxmjOGKqFoToIxhpSySkJohQRoPqsvg36ng3Idg89h/HzQIguneuSDJ4hd0wKmWoQbuIOMbu7OychMfVI40RUuHoWN3u+R/lb/cIFwlit0yjzDg9hKCZFliQNELkpjdS/cQZqpZZgKZsOrF9f1yF10bhKgP7G25E6Db9/IESYQ63I1J4Mv4AgqBBDb11raY8b1XszJz2Ycwpsfa261ja0=
  template:
    metadata:
      name: alertmanager-pushover-tokens
      namespace: prometheus
    type: Opaque
