apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance

spec:
  encryptedData:
    admin-password: AgBb7tdwY7XKxlpppB606IU08b05tQ9QwfMCnypU4qYMtqqLoDa6f7ATVWj1v7Pc0U6f/HhHLzP9fKmBgZrkLTTtE9msW+DTBOR66EBTCQbY7wez8jGQTyPT+FSXJVc9XTgSm8nm3QZ8k7FB5S+FNAWlHqgMC9Yr9g/Q9SqL0O/ai+3ocUMu5Lv4/fZflwObrj3podlx5WA4DMSJopCjURPTMKsvouqs8HIPFds9Y3UCex4IQ6C1DZieStsEWCBkGQS6g/VQZkYNeyWBdoinhmKBsAP28tUUm7IaLsHWaLRdQUR7Dki4sr622qx66f+Q33Q5FXGch6tgRcDGxlhC7q/KWhdoirbwfl4DEE1qQkvPn12LSEV6AybPbUjjVtGj59GAudydieW1xRkL4DrcHc/j/Hq6gKoReM4bHVGJZRLikE5gAT1VJNuG3GT2turiMsmOeyoPONI4HwJZRktETYp8CQRSdDEw8/rjWDJzSIKfV6B8gLQ7ISiTb9zGOgHVXu9PA2fKKLKmkyMgQRF1V8lMCPL3spzNYCM05JJzFRtqh5PYT0P2NgZl6Has692dOqoQdWaAD7OskzU+8SHJpvY94r8K7n/Xf8peAUlIahjzGYCp179rhGFe6Ukwb4InySDEwLoONFlys6O7h7my357buXBWLVOATgT6YX5ADh37ujYOz++GZy6vB15Z5oVkQfOPXhCAegscJ6UsItGZA79fYUabhQ==
    admin-user: AgAzHN5pjwEIm+p/1d0gsN6CcxPLVwfx5woyGKSsNUKgf7vMAQHyo+ASSU128jKAzDvX1kFYsGxx5doywzVkPbel0kYOxAvLwGYy4Aiz7dGJ/ZiiFRHqXEZ8sJE86NfXZgFW+65YC7j1HWtzWZED9E/+wcoLYhgH0lOR6ZzoUAQDLodHP7/SNNwHaQRL1BCy59FDyMiuNpGWtg6Qe6e0oayqJjVAFhj4j2/ieuzgtR5sKkpJgcjyaz2tnyUG0DD73bIt+NF7BLghT87D7RBOTzgPYCGDbNPXwXiGYnMzCkW2CnUFV8vrzAuAOfRQiwDFtZIvvF8mefzmcvcWvz8BS3TKBSQXYZUi2IKUiDGWQs5u4K8C0ofyCEPcvt4iHopnlb9S3fj7rH1Fzcb10Y23m06jQ0FB7hSt5gRrFZuc8Q/L1o2PLZU5Y9yircceeMcEVoHYYAscTP5cMk3iCdImapofE3KVfN74gO6YTCNMm96YSFPW/4GN5h3oDqYq0ktc3TFG4QzVV+zO8AMk5m5MNliyxEDfjP026KQpuEiHrENf+bNgN0FX1FiWnc/LLmgErpqMNLAUbuS+xXkMvkGuvc62YXdArQFqPHEywNq9MmIPaCQg6xXSI4mfG8J7pEQ/494erboUpUV/dC5snntu6DAgYaKE9Eu/ZF9rt/6/dTxwyfCuQfrW3uwezVY+CYCJQEIk+H1WyA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
    type: Opaque
