apiVersion: batch/v1
kind: Job

metadata:
  name: initialize-rustfs-buckets
  namespace: rustfs
  annotations:
    argocd.argoproj.io/hook: PostSync

spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      # Wait until RustFS is reachable
      initContainers:
        - name: wait-for-rustfs
          image: curlimages/curl:8.18.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              until curl -sSf "$RUSTFS_URL/health" >/dev/null; do
                echo "Waiting for RustFS..."
                sleep 3
              done
          env:
            - name: RUSTFS_URL
              value: "http://rustfs-svc.rustfs.svc.cluster.local:9000"
      containers:
        - name: mc
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          command: ["/bin/sh", "/scripts/initialize-rustfs-buckets.sh"]
          env:
            - name: RUSTFS_URL
              value: "http://rustfs-svc.rustfs.svc.cluster.local:9000"
            - name: BUCKETS
              value: "authentik-backups longhorn-backups"
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-admin-credentials
                  key: RUSTFS_ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-admin-credentials
                  key: RUSTFS_SECRET_KEY
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: scripts
          configMap:
            name: rustfs-bucket-init-script
            defaultMode: 0555
        - name: tmp
          emptyDir: {}
