apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-admin-credentials
  namespace: rustfs

spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAvLVO0AKj/51pjoBJIiXfzjfhfrYIWR5Wat1JEznur64WjpnMrU/COvVZteLTI5BDW/z2E49YXK3I8+hMBWYUiczV5s1jqEEiscCyPIAU7ssA22+Hje4eW3UkQ8phv6TgBM5WaSwgtvuaFUJh/lF5qv6lvJ8XYlrvgXYQTtqDk9LSGYSQF6kazSan5aS2MhgOQqBY2sD2Cemn3Jp0hIOM0X8xghHM1fNBtj56KBmW0Jep95FKkziYMne6SCCLxsT0ZBakcYDygA5TPtMIw40+GCEitPRYXh0Gcd5gqtBSkbTi0zI40Siei+Mp3WP+Rb+vgcJBb5742jBn3X3+cZgA6FYlJTzszm4sBFasOD0yiSSe8/L3P3Zb7QDimwBg1bTsofpOWHZNbj5nLQ10ZLxhfaN7G/Gf6GiEf1Zs9RzpwcQL6sdvGWuYL9jbb3Tq8I5zRV5Msn8yjzZRJ4wd6Gt21NiXr6FojW08kDsF2n2JBbpuSbnhP59hi7MDb0fzSJt2Ox2LnIgERWuqSPvwuiOYYL97oELp7GfuOOszJC0Om9QFxhEIDIfj3swfxvCHVGfCikE9EAYWPHzlnE7akHw0sjhTtwc3pJ2ZzyU9wSk1T++URKfjXx9Dqcvp54PeJYmzuP6GmmyHzijw845tlRfyDw5oefI9Aj6D93yUpjz3xi+l0+JFp7sGp/Sv//MAiWsphUTx4u6W7IM/eJA==
    RUSTFS_SECRET_KEY: AgCTrNSV3IQswDE3l+1+ZokeJ5T9JIeKL1H9YFOddO/Jb717YnGwUcOkglldSAaxnMVuNN16uXLktbSiovK2B8qtVoL5NEsT4waeAx65BsxX0xTMs6XdaEWPyw5q3UTDLBfJe2zOHkZebK+SO2uQLq1zhQ15my5kez84D4xV5WVOvVke0h6mjWEM8Piixj11Ilrzain17V/vkddyBVqTMPLELHlqWqnN2rfxQMJT9lxlfn1ulmgIjgWxCvZ3Xlwv1bDJXkIy0TcPc+TSCzORTaec26O3b294wR+myTKGvE5pcTffXVKRtoCktxLcneOk4FB2SQJbvsbs5pBOTEiNK/UxCqwiNpoyXig9JGt+V9WfnP1tsORep250/72UUZCxHJxbSFdj4rP/YvBe0K/mijJfUmoJ/cs4kjeVZ34BW0i3HSYUvT0e7CPeTJS6sBZgpwOFt0xZvhtj4a8ZYSOYLCliLk4IAsu9JmOIeScPWv6GWS4EpuIbW+m+l0LPs0p8fkbChUeypVFKmaUyTmqOC/CWm4OTbDxDRIVEqEQsT+AIZUVm7E2X+CL04+zY+r/C+cv1fNUHs6tGIZkfOQQWnyxWowVdDFId/Ri3A8F/LuqUIbs4BP4RJzuk4+c4OqNv5iAd4CnmbAEenXr5G2EZHoFRdhUn4Bpkoi+Y+TgM622wG6SkS9Q5hzsoW5OVjUVzMjOUyZf0rt886xn6xHy1sOCa64eYsp+TJjDnufvVxH2vY8AW
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque
