apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: basic-auth-users
  namespace: ingress-controller
spec:
  encryptedData:
    users: AgBQhTpqrxDl6y9Et4aGMbk1G1OVegPcDwfEjBM9/KlkOLXcNqSDBL9DAs+2SywMe3U3X/p+B8iSrxNA/MLr6rvGsL4Jyjv99lqDu6zvqrPgen7jftKbeBRvqPC4JQ/Zdd55JCsgWH4IPP6TcH/KIWT7WmlZ1gExmLnp4FXc+GjuXPfc8i4tpSOlblkEzjMVbzl/LM2fyH+NQfW3xTttAkfb17WBIOYSG23BF19mZYl29IY8xXTcp/3X9TaqJdX5DBhSoGL2nlC4zFDAIt21oE3K7g5P2ECKMU5XzjZM6ZxsOlYXiwdeNx68YjyUMEBtyUueyJYFD4R00Tl7Q7hkp5hLjHct1CCQmSq5TT462RnjHrM/GKxymRWTOaTNYxF1C2LUk3Kg+b8iTxPiys9q+sba2MVZ6RsVviG+wTG2ds5ZqJqCoaoXInK5UTevI//RTpB1bGjEXDe/yblpD10RLqAQfnMASLXsmBMlQFJ30a6NOUmJUUHdDkIOXM3pE59mzs5kh+IskzHfhexw7HYE1GxvvKnT6Od9taSO0g0pfaRBoDHKIL+mORypjdybBGdxEvuS3atMoXfuxExv3rTXq/YQFDYS/D2RwgNneVHr0JoDzHUlnaud+qs21YEP7EfRKu5r2RdsJy8c96sV+GKO2+Vh8Krextzi3QjkfAb81DzuUvX0CbZzIIecCwJ+cawBjQ+4k75GjWhLLOBR/MQMDGVtdmH+pMPcvQPmIihGcP2KChq+t2+pECOldI9xD94kAXTIu6km/Fx8WDDueOcMrfM3AcKY6NCOV2P01g9V4PUA/8MI+tUCg98BHk5LhhNWh+kmqHH4HydA6zdhnJOAE6XoGJHQiyGQ8xTccpnY6QmvLx6h+EBdQFYDasW7kl9DsMiGRkE3ymc8kkO+mf/LXttG4vgaAviR1KApqthQfnIOIyJh6Q05c/vAIF5gMjjlY8MHlnDT+g00kScr+IWRc+310kM+5Q8i7Cf1GJkQMg4jDGCHMQ==
  template:
    metadata:
      name: basic-auth-users
      namespace: ingress-controller
    type: Opaque
