apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: basic-auth-users
  namespace: ingress-controller

spec:
  encryptedData:
    users: AgAaz1JuRCpxQagWbgHoTdgPmJ9Vbq4KTMV9PBa8Ap7cPv2vCqa/s5D6ghaEV1OjsC2v/yYat748nZx28FqCRc8q72TdV5jUQSh2YfeJT/e6wBglLQVNQLuXzcMvKHWeQaZenPyPsCC6yl94FvJYYlAemFBw1I1RDPai6vfkTXQqDQaxuHS7cf/0oH6tu99CeJBgzciEVLdSGUIdhwtRAzHh/i4+/12ZMqudxBtq/+jBIJV2JoFOoXZg56ITNocqXvTWXn8y0xCinlrUc7uQ8Lqmk8QgdPreT0710Ru/Ku+LuSNtCsKrNpLC2tjuyDcUP0zKk215YSxG96izmnbs1RPdfQBVGWVo14BF6t62MNLByc5WCVQ7hHG5G4X3E+xBhlxHK8nSGnF9nCScqtJcqyHt+GCTHVlW38oP/RulR1d+EHzYEv+MB7QnZ2BLLVJs68WNZRxOU0BjKFeOFj7slB4UCLgzW2fGG9y9LrfKT1qBmx2JyuXx9cg5EFNGXFqzbJi0PXMh5zSeIerip1Amw4xaeaml0vA0JCUIu1nV1DkyIVwYh4NDXa+LZgATyOaZ9ikhZHSylaiIwnVqjypgY9Bp+MJPWEWP60WfNvkrUIqCHOfBHaJcY7Z0a+q1KTrrQXmIqfC4axRUSxEAT/1i3n5j6wLNFdpEzeSSj4G0FTenzWDKlUiAUQgVDiqdiiLTUrv3Ci9cmP3XV7UklK3C3/LsZXjmyW/AnjAhjJZpb90PsJcxQfPn4PtklBgXUV0RgPrdym9lb5WPoBVBsEzvwaoLv5moij7Kxz/Wja8h141OgOiVN5HvLEpR8ZG7MH1HJurBRupomxbh0s95UR8bTdEOnk1IYeJxLSR4wlOEHr0YqZWicXWzK/f2BXdNCNG5MfHGQ5U3kJw1HflObOrIx6ei7+J/msQy2U+D/ffGqm5HH/nnzZu+FkjQlvXQk/nCGuLk7W6vTmXszdbF9CLxeMTcOO8PmYABndCuPfu2pC3+AzgbYw==
  template:
    metadata:
      name: basic-auth-users
      namespace: ingress-controller
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: crowdsec-lapi-key
  namespace: ingress-controller

spec:
  encryptedData:
    crowdsec_lapi_key: AgAJuTsLoDwJOWmau9xJB933ecGTHJm1HqxyTrWKueuG3sEYlWK8nsSYaqsPIpIIOuEEouSQyo2YOzgcS9SjC670KLAM5QyU13C0r8yfIfP9qClRdr4hIsoZ/P+gai8Zl9vzHxaO0k33xkuEbUgGTPlgkoXq05kgEe3DQ7lL2Q3kjXpAsECaR6fv8vprGxcuMjWbUpYv7FXX3xPBuaFn8Ik/GBQFvhx6N3+6RQG/TqYChKzF17DkX8V28K/8y6UalXlPny39XyFG1sdSpxjyj2Tqj/JD9+SUqj4TsogMVpzSuEidMaY9dWkZdSMBUmt3qkHpcNzyH9SkqUwDXx6d35cGmxa5nRiq29P4hsZr2DRW6tQ1UJfozV7hJ1AqURgle1tOXk3+YLjJrltjiJ1hHl1Z3YEuj4ba3fcIbDPYWGTjLAfA8cTPNFrQhqz0tWCe0cQrb7r6lCnWB1DhjZCBz5lr3+ya9QL+fOfF7Q5aessWFcQT3l9qE9jgOKcVOY9mQALblJqAr7l6VTabnzO4I5k+KON5VuoBDyhwvald9tLEKnWMkW3BRPEvGecCB6k7fMp03dzpaBX2Q0SUnbbbIkEWIq7BKDjecAya6R7W6BZJhy2XkemYMo6DdSl2Ojx6PlLbQMW8wxl2VryBJr5w7G6PBg8VmfajMqcODyQ5Jf8vWr4wvOGEQ/OfsVmKH3hesouBQ31K9v/1PcdWo/SZb8AY5dkGOFsOBUz/HXt6xc+Mx67z+8p5nA7j+zmGvWnrgFp6Rc9ylfG+gGAg16hGmZ8J
  template:
    metadata:
      name: crowdsec-lapi-key
      namespace: ingress-controller
    type: Opaque
