apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: basic-auth-users
  namespace: ingress-controller
spec:
  encryptedData:
    users: AgCgpkXrEwDniUkgmd4QtFLH2zbXR5pwhpxvjSWZK5jQrF0HaWgh0XydyVoiZvhENa5lcD3DIQB8zUjPfVgVt60qSU/aIwxcWie0zhsOOscwbg2XPTitFw/7MiMqBBxNj565ZKcqqxiqNtViU6xJaOlPfPpPLb/LPjUERhN85VC40rc7jG907vH+cHElPNPb159LA8LTOoHoE0pvr7ynlQWkTmO9Xx9AM9djv8dcG3YUT1LD5RdWmUi7GWzX8TmF1ujA/ceCePf9nXq3T0legxY1WUl6mAk4z9O6ksESHBrcOpN8oI2kRGPtCr0dFx3tO84ZznZTl8W5H5Eb6CJfvIcuyAoGwUoAaTLRNUB/f2OznXRWuVuvIeaP4wJESy+Lyrp6XuamWcY/0v1bVnIidH0MSbnVi5GVpNmQVRTrQudakHY5GMyaztlUNlY+3QU+Hj3pEznYK9MWbA2/pQ58kiC++GAEQfIzysXAsUQeckv4aPD46+NqZF8OXFC4B5mSr/vwjLe7qWwXKlnSr4ynfXwPrATgmSqf2jba4NthbTAdn1M6ZBHRz2TWLBVbMBA8upXfEv/rlA8XqFr+q19SJJklL33kTZ7e8Wgsu8E0RGFyvGZLDEVD5x3sGaIuQP1p+FVu4fyAkP2DwlmbE3Wx0UUy3QoTyJw2EZ5oQ/O2cochCh66uIKKjfYDAT/W28fqZxBiyPPkUElpk9WnGQrwXXQsfI+Ro9Mosbxm8pGMRmpPJui7JYQf2ueqLCHjKxLlFC2JdxnsbpmVnuMGIZsCqGrHeCmF3T/R9QlHdXKjlXH5GgqDYB/OAF328GaypTLFF66KquezX1+TUyHEZVG7oi1OEvsemnQQqz2qvaP48JfI9Zjxs6JmPQET/Zvryee7y3z7ztJhk9bXpEcfVsi5ia10Pmppa6a+XrPT6YuGv/azpsIKI72NjcL6Qk8egTfBxp8UrFRj7KMAetcsHOshxbzDP0HOrmKSCffjsp595WR1gB5E7g==
  template:
    metadata:
      name: basic-auth-users
      namespace: ingress-controller
    type: Opaque
