apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cilium-unifi-bgp-credentials
  namespace: cilium

spec:
  encryptedData:
    password: AgAW6wEG940YXmCfKJpPfotKBeBV5KJLe0iWTDOTnVcoxDhuV9Gdo1f6R3aFBUpL58bCSfA07R5fkACsDrbDlu2rtZMQZd+fj//Z6syBA5CF1XLh1/EgcN6ivAtnWZQLyzO8cm5cTo93RU1s9ip3ZLxypoeLSb0Rb0I4lkgr28FoUa9+x3Y+v0JudmyyNgax8poZRgw+YqLFEv+OvMc1gr2U8b9+2d9GlaVq7ozyiMZdURvOOsuWF44hHDp0CfZ3o7BawuBeaSMuSL5+9wYyxJek4iEhUC8fQGUradwbP8j3Jq2iAPCBhzeBej1rhohgMlAMLMZVcWSoKxAd6CwiC02/QUvE5RrovxJi+z1BijMR7C+WNrTjva5t25qc9QMzAgQgokGWPv5OhCYXlxi+dL7K/z3n1NTxPFLPCo00Y0u5Q0KogTHyrDUyYZZsVI3g22YAP7x8V81AQxx/3fFOj7M6ZKiUKVfA0Hf14BEhSM6UZcnycaFSDb9ZT6yYS3h1w2uu/iR/BywOmv31pHwZ+UNyK5Y8wt03sBU1sWSVzH4EUaDfBMxV9G/ftKE5+qRu6KYIpqNq8ag2WbmB6TO7A340WD9KSU/bJkXHNUfHpgHjPfzS+WKcIi1XSugLXXz9RsVsvUNDY6oMWa2A+P96+ZeXzc1HuveerM9CJvrgf2qchlD8HaUaufE7agY32XYFpQNPpEtKCdZW1vPN4QjTERLI6+2vMw==
  template:
    metadata:
      name: cilium-unifi-bgp-credentials
      namespace: cilium
    type: Opaque
