apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: external-dns-cf-credentials
  namespace: external-dns

spec:
  encryptedData:
    cf-api-token: AgBJ8H6Je4PcgNWgwhPoN9MOJw3TJKq4OL2MGSojYuhZ2TlbzsrenKRgP45ExjtvkB2PcsEv92fBhUUhpPn1m+h2HzlkObz6nO+Ps2OtquaUpzG+Z33XtWxuofaTiNnWGVsWFwCN++ZQO/SUmjBcckcFFIDc9vp7BkCGDfQDs4ernG5lfPBVYne0J2ArbwdUQa2DyIK6LGNfDY2VjpMYlKS6kWM9hnpkBxphhh0WP4mxtmQDtYlgKhtnj/4vmVQeeaz5lq6qz2Z+G+SXaitZVoleMAdGCRK/DYBtIWLVqE8GXRgOEdOu1AiNy9Ym1VluNbqk6dQpifkJDcEVpuOLm3PvtASpWFV5kVLLgW2x4VquFLkKe1zPiuMRzdDPi1mO2btmJITPrfQV5EKz3HNsttaURn8jS6emJntvnw6U5TH3LE0Hh5wDE3rKPWy14kqS4LLl+4PZQrHnAM8FqEvrgkTbDPUHG5eIWUUsWJKfQX5N/hSKF3lbudwH91AMOfzYIaMC0meNqwVxY8qqC6Oy1eWTZI4veQopT2A+id2mlp+WR7mH+WxcKYm3jiPviYLc95FVctJLqeN/Pc3IVB+N/lgFl0rAV78792qbO2464qMuU1lmQzq1pUL3lIuRg5F0XjAp5kvWN49oPmUTH5oHpFjAxd2K9tDjsWKOljmh3zoGWtCL1zXiBJMd3yUjyD14ICi5fstisWvAetwTM5t+1/TtfQi2E2RH6l93Yx44fGfgpTWrAslQlm6c
  template:
    metadata:
      name: external-dns-cf-credentials
      namespace: external-dns
    type: Opaque
