apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller

spec:
  encryptedData:
    unifi-password: AgBmKD8SVyx+QhbQLAFADfKAmQT0sr4sO1OOluwKOkGeFr03BAJcSp5k2/snEB4NAMYCTJH+Dm1ZvXykPGGm37QV1x2M0arK8e3HCBhbM9lOlVivq58li6J3o0xLS95yA53J76hrWJud9riYibGmkCqNYUjLSTaRHQU9nc1IcSVsX3g7wTl2qN/meuT2GvSeGp7B1dzi1ESQ8ZcKNOK0rKWHYlZdaPx5pLlmk6Hx08AebqgpmV5asrWKyIKdqjtLGdV5aVChONZskv6ggP83yjSBkHsVQFSuZTgoybbAzzKF51I8huN3e8iAyheIp5SGVpAflE6VpZf6B3WF2NtTw7QfdLLd07fAGuL9890I7UbHWDA96F59KhZSn1u24cjV+uJPOzHjVDuLPrn/vh3Vsc6nEch6KNmYDQ9Gida3FW5ZvMmU/wLPBYG0Pm9yuhey2ns/Tuev4LM/tAwY2dLRMltTR+7KW5zV9GtEi8rXu0V+1B39oI2xeIOFw3NXgH7rF9Q5xsy4919qvWmnXM2JpnCXn8u0UTskelzJIRoD/4FvMm9qKPuseDUfm7gMxhM87XhuGmWAJ0Yo1ofTMfhGDMHTXJAvGhThYCeAsR8hfqN862nGoutrovwt8wefokm5/OQRrvKIbsr+63LEYF0qfGebsu/AZ2lqKlz+bD/iekBVCCvCYYQVU8kNsRbN2MsBGAr3fzgv3c/SbIV2324WKWBG4PuuBQ==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
