apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: sync-cluster-secrets
  annotations:
    policies.kyverno.io/title: Sync Cluster Secrets
    policies.kyverno.io/category: Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Synchronizes essential secrets across namespaces to ensure
      dependent services availability.

spec:
  generateExisting: true
  rules:
    # Syncs the DHI registry secret from the sealed-secrets-controller into all namespaces except sealed-secrets-controller
    - name: sync-dhi-registry-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - sealed-secrets-controller
      generate:
        apiVersion: v1
        kind: Secret
        name: dhi-registry-secret
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: sealed-secrets-controller
          name: dhi-registry-secret

    # Syncs the ArgoCD OIDC client secret from the authentik into gitops-controller namespace
    - name: sync-argocd-oidc-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - gitops-controller
      generate:
        apiVersion: v1
        kind: Secret
        name: argocd-oidc-secret
        namespace: gitops-controller
        synchronize: true
        clone:
          namespace: authentik
          name: argocd-oidc-secret

    # Syncs the Redis password from the redis namespace into ingress-controller for CrowdSec bouncer
    - name: sync-redis-password
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - ingress-controller
      generate:
        apiVersion: v1
        kind: Secret
        name: redis-admin-credentials
        namespace: ingress-controller
        synchronize: true
        clone:
          namespace: redis
          name: redis-admin-credentials
