apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana

spec:
  encryptedData:
    admin-password: AgBmgDvA/6IG+2fGOX3W4Ru1aDA8KRNoAgltrGtPOIYO6z8ChvYx8HJAXjlWHhbcyb6UB7ZO9Kch7Hb6yjCB2ePerNzFU3drH5gxOAsXwqp5XhlOjY99V13oAxvKJdX0MHITmXohLXJZvCaW66q1JyJhiI+YtpFQK4Yu488OisUVB8FSe9XaeIiBLAVwK3plXfyKixtqnh7dMSCFZxdA8ym90qSKfu/PQdNqSmVb7BFpyKrcUjmQbE6efABtxv7Edpse7aAMaRdmOUPd8Z+A9lU5xBqCIG8FP/W3itcheGakTldT6EX8YVXtPNVecaqYm+vTnNvE8GposCWJQu6Z04DEfW+lAtuUfLmCsBicujD9rRJ1RsDA6OtJIuhtRBruh18E6oYN1rGPh2gt0N3c0+FuOTkNiutDEExs9P95rNhzatdgq3TyGmc5uHy4ixpTs5bTzMZFwZwLms8b5wFv5g9RYuieOjWPxVVYB7SYOofFOszvJwaR6fPHsxrSAKGdvpdUkRU0IsOdRv5nKwKfTqEJ6ZLa67QXIl2NHaLY1HKeaz+H976agGCklhcRz7oUkZrr+2Ud9Q+URPHaRoQxTQ/JKU1F4RN5Ydx8yNbLuxPu1vHUrXtaF4YYGCVczR0cHjr8oaBrPZaq5yucwfNTms0849SrpWPAKADQFHlOplec55AUmn97rHAiPh8EkYgCGua0XYhsakQoo23RWYkY2OOU0HEwQg==
    admin-user: AgBtCf3nnNQzbNMr874edWgGhBXHFtPuLvQpW4fpt/LkyW42y6fulhvgtYEcd1iPqNwjAgChKy2NqMG9RrcefFAGBRdTDh4ulhJuIV5JQ9qDvC42ClNKmv550fRyd4+jibX5RQ0dJt9nGfs8qhAF4CRZSSIm0h2L9soYE4Ulx9F4D6Bkm2dAu2nl6/52bZ6uxA9WBYbZKgETZTNjdjhJRI0JmyHTVqZChLuBnXXiMMvhUm9zQIN3uxKoWGxP6xqNX15C5E7F8sa1xBSGNy9jJQFOwjf21hlyJ16kJ0KnNhx8ELO7AulsuVLwbo7If8NRxl0FvkdZSxjaSnEeNkuK0+34QWCIzfpxx5guo8VTTeW5FR2av1hKP24RmOojpYxSPA6S6rjrdaSS4ckjvzBi9CQ6C85OxWUbpL6tglWUHCBWd410pOI670yUPh8oZTIAGSdYVnVlfUejmSo2BWP0KzK7Nnul9jH97SPNC/I7v4hoYljUCRziNhMj1ktyASaS+2r493LjQv9ESHBe96X0Pr2fIthMAD8hL4RYmEhlo8Ej40UWtGi9l26jorBW+SFGUnBdjNWy3IseqrER5+hM7q7wjJh6s0JhR7a1NCuQWcLQFtHO91fHASxSN+kg18yYbNtAoEDtne8MkpmQzXn2bvUpFb1PMyT4DIHr4BWuNh2NqLY1+lb2xsYwXGWEpaU9HRyn3HFAwg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana
    type: Opaque
