apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telegraf
resources:
  - ./namespace.yaml
  - ./servicemonitor.yaml

helmCharts:
  - name: telegraf
    repo: https://helm.influxdata.com
    releaseName: telegraf
    version: 1.8.69
    valuesFile: values.yaml
    namespace: telegraf

configMapGenerator:
  - name: telegraf-inputs
    options:
      disableNameSuffixHash: true
    files:
      - inputs/input.knx.conf
      - inputs/input.mqtt.ems.conf
      - inputs/input.mqtt.warp.conf
      - inputs/input.mqtt.solaredge.conf
      - processors/processor.knx.conf
      - processors/processor.mqtt.warp.conf

labels:
  - includeSelectors: false
    pairs:
      homelab.app: telegraf

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
