apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: telegraf-credentials
  namespace: telegraf

spec:
  encryptedData:
    INFLUXDB_TOKEN: AgB7QH1Y9/D60sl66WAOePWN2GpA1b80oGym/mVKOyMth7rMncOhRAMZvEgV6bFbdRDx5fu4EP+WzKArKZiEqVBLPhyu8Rw/xLt+AC+AGEu3sn5xAIDgCMq1YcojTl7GoRfBwWo09zdEJL0ygf5iPgdurbrKZ3EytZ1tZIhcIkeQW6czhKtitRI7ZXSLt+bKSfvQcmT66C/EOFd53Qr7xslYvouJKT/1/3oTiqSqlXq/I3iRL/+NfAVeHqj+X/o46HHCo3+pLd/icArzUKA38QeALkmdAl+W4XlsV/i/FeRrAEREHTqs5eUysuoF3pe3GuhcLS/KOhzKqxxoAc3R+wqoY67h/uAU0qt0t5WxkNlMBxtpGu5y0PfVjUJ73198gI7/XoqMx6c6vsKnMd5X6wlgSRHpAOCwOpi8aGF0SDd5k6lcVcmYRjvJxrJMsNwl0eVLxe7iNaeuUzXeAhSDYRKm3cKP1fVTMXRzFJG3OCWITxMfVhKftWKSuiS+Bh1VT57MIC83mOrFfa6Q3A5jR//rnKeXWZABSROmyI4s6oAfy0rdn9cSO+nbagPX2pREioA4WIY8Ta1umexEosu0aEyYj18IvDJGaB34CUtpHq7am/5LdogffET6uGhE5rVy05fbvw+xmwDZ9VOJT0xLI3kDH8XRcP5cBYceMl/8EIRxWOajyOf2Q38TZADDvjATVvtm4c3ZimokVDOF1meJUGEm9MIu75grzw14ft+GUX5M+cfVjCtAiq6nvkTuF+KklwB8yS4OGEeZRfFpgqu4OyllvIyz8ecMeMvaXzUHXcR7FZbtpnfjkYUb
    MQTT_PASSWORD: AgBagMGBRO2DCh43rXOpLeR8UgZ9NrZC8TNB3u6NK/PnFcDBWBPnfXxnk6iKQVS3+hmNA02hu9LoMtpQ89gB2z53uUwDtIbupq/WEVTVUptgF4nh4m9CnK4LE4xc1nTllTMNEcN9PcEuPFGWYdQ37DcVwJL0Io2w+LOfC4CX5l0+F8QLpQJpSbutoSeoJqUYwJRyErVi5eAh7/Go/45l6hDbeBu44IgIlnFBV/T+g6939XGbmTPNjYNIvAMvLSyUS05l/k4NJNe/boKWd4aTWWXq40daKDB3iQUQ2ca/F6+NGhbJLUUax16WviysSy302Bz3jRZx8ZgVrsnVW98Xl8dVuQwK4Nsgx/SomAxuJpVLf1E5mAyCYbI2IeuPxbISa19+2MHm3CiQ4oemFV3wlB905b5KJ9MRMAI8nr0Adi/GDuDK2HNLusFsTMbH7A6B8gSeF1db6u34R0q04q0bQztP5hxr+11A9LxMQWpDQq9alR9V6GkAUKUO6iAjcBNxpVZKZYfrck4f7/a4JJrRQa1+cIBJBKyjGKjfMKnPXQVm5x/8Fo4kEbYGn1aPhLjwu5JQILcJK5Vt+zEBWajyPpAuvIdkCX/gYCmFyNDaOOofTWxMZKTJM5dvxIseUdsSdimuKXMheXdhChu8nwmbvz7kg9U8wg3AX7ajqlTHrT2A8HaFyG3bmLHqwJKN67YeY+ClilBf1YX2Btf3Ti7UikB1vIlJ1w==
  template:
    metadata:
      name: telegraf-credentials
      namespace: telegraf
    type: Opaque
