apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: telegraf-credentials
  namespace: telegraf

spec:
  encryptedData:
    INFLUXDB_TOKEN: AgBgoUz5g3jV3SQ8FdCsmX7GZzLDt+raVqpeeh6hHluL9bV9UUI/cwSYCj8Ac3oVt6zMDfON32qFY5PdSrNSeCa0rG/wAe9M85ZFUKJwjvvzowNe7FibehjEWZeFjzyFEXty4n1tUv+2cglnEVb8oBMbu4WF1CaQdaCTZ1eOCMTHMiBijZPkrvHAUrTXJYn2Vsk0tId1axoGVecOdvi92fdTEzY/YYxGZT1Xi3K5hhift8ZoRV4XW1IoO8nXPuQByScThVi5JFjREkx5IViBxpaztvqJChlUHqCjkl14pRn5BIZXy0xnkkzP9m3mXZXOtG1I8UFP5q/R4cs4vu2t/whctF5MytELlz0drumRFl8TiGIfhldmKDZ6XzbEntlWNgDL7HahjmOUr4SBeCgXsTLAOm6ojOaOLH3ok0Hav0lpvY4RHH/igigGBlaCZknkT18LZmSnuSyra+Va+zv10xDXAXwLCKh2GzT8GXeg739+oIvAD3Xo+U1SAKDpzu4U2nQowJjH/Ly5FBEFpFoFiyu7HfCByyfZ9OmHhxW5W14RL/MjpKx+52CBscAM/gYgnGleRSXGXevCS1Lomlt2hZrEwKXCs4EXF4cIaU7fQJSIOCt8BtqcR046SZwxV6gSLBeQ0cBax6m79SDL6JNj9LsMZWF3lkUe+Lo+vZoaFcOqrKpgR4yMRx1aqx/mOgCsqCjJ9vR4YpKzfpYozfhEB1BOqIs0JiCridJv0ePzi6tu4Z2ov6fpQVZm2AKKBPmKbYetcI2JR8mWc02hb7fLVcBHv99aDDlw5UYjFf7nhnk0QJ3L7g6FSOm0
  template:
    metadata:
      name: telegraf-credentials
      namespace: telegraf
    type: Opaque
