apiVersion: longhorn.io/v1beta2
kind: RecurringJob

metadata:
  name: backup-daily
  namespace: csi-block-storage-controller
spec:
  cron: "0 2 * * *" # Every day at 2am
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 2

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim-weekly
  namespace: csi-block-storage-controller
spec:
  cron: "0 1 * * 0" # Every Sunday at 1am
  task: filesystem-trim
  groups:
    - default
  retain: 1
  concurrency: 2
