apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cert-manager-cf-credentials
  namespace: cert-manager

spec:
  encryptedData:
    api-token: AgAnE6gzoNNE+VtV7iNpBROZkSo38Fxii6yCqmOTVsOvUbpmZWGLaAk53+ihmooW0emYvWbGTcOSEzbzwKdI45rknHEE02lypUt3lTxPP6O500E5efTSbMtjnrtMJ9wLOSPu/w3aS5N8DEoXLuw7RH2i6J3fuNr3JFQ5/jOQZ5rzAv4IjfPJHxsStPhbq+rIlsyoyW8SwBFi80jQob91aL+uSRT4ORRWU0iYxAoTd5NLMElk7lRRAQZjSehAaDNW1ayaV045rQSgoDLDEHKIDNFFO6pe+v48fu6V6zJaDYs9wxRAKFTiIjoxhKLtpFkT5aHb+K5aah9WP9xJTs+INKrNqSBOhFoOm3lYyAlI/GZDsxFYSnjuU/vEt7ClaXtnT/ekxmpGiD9EvtEU1jkMwjpMYHQWX1P98Zd7V8IvHal+GgldjdrsgU9I5xSuTCEcjXV99HFjMbZpM7nIaLy1086JebfcvzXScb+BIVVtHw5Qr+hXi0DgnptPyQFzd39AKdPUg/tEGaH0qylMUMnzY4tqBwihf+C+/WzTMjhIQfURmN2DTIsQY8Li4tKyhXFX7H/P/03pAebkt0JvGSgojRpQX5F+UL6Ut5R02H1BGhCnh8wrLGR6WGqyMnlW0qN1vvpzob6nsJ1a2Tub5MdxkaapoTkD3tvwedbFhIqUM0cIReb9f7tZ8qPKxcqt8q22rkGF5VXUWiGFL5j9WgGImP98583mcKGZsVeOB2RRAdqqZ/kAOrX0BmAo
  template:
    metadata:
      name: cert-manager-cf-credentials
      namespace: cert-manager
    type: Opaque
