apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-connect-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgBNlR25gKCgDwN9CtubcHdwKXafRcv3FJuFUh8DTo9TpY/e0SIJD5xsDs1zeTMnq0iV4zXAAnTMELrDMSYAlCr6V58r+bg1ADM0RPGIB7Tre7yGt4pthEs+Iq5nd94m3QirMD16IjIlC6GFfjhmXplHMo6rFxsFypY3KDkV0ebcHRsIMD1X/xBMbrmp2SW/q/y/1fL5XU+j0l4vkrETCZ3mH0ZGQAePjNagHnZ0s911mtuGAqi8Bx/AVLED639xex9Z60YlrVNnVljDXnb74hH7w4ddBQ+I3ijO6HVbQ739lORtXf6l6b6IL3+5U0BTFR4OYONlRq6cm6brRdXWO3DEujiSjR3rnmOlZ/z7/b8EpppKaX6yao7LquA3UBf5X/kbBjijJrAnFjgqMIX6GllibawPKtTDi0F9cqzdpFZnAs0wCxLZwaphKhVPXZ/rRXL87DyqpWtpQdkjW69/ilZHn6RmHvVEZP40H2AQQnCFy1RvKHNSaIB7LLGwFq3PiSI5+SfFUmUXxKcR/NuNmj9/4aWkz9Afn2DOY+3q9qtYCryCYZWNA1qK2CbWdaU/1NZzfXKmgVDR+JROJfVSP4ZWazJH9+giLoAQYA8KWfYA93X14BsQ6ew6qrvYM0Mu4IXq062/T1X+GrAyPsVaswya18A0B29XXdwGcwy/jXaRgUqEcLAJhjizu6CHr1VcC5+nWaEMk0OnFbcEHl6DP5sVcPZBiZ12yO1QL/5U8NvbsA==
    username: AgANjQ9Ty8z0QHrAY+4G8pQOfFP1llNJtLTMZo9IUK82EqFevavOwzla8/MllZ3VYt+Cm5JGQKqZZaTTdlmG3NA+F668nNRIRWcDix+YKvpKXAsMs+E3fbh1OQ6Kj7F7wN8NCEyFB9DVvWMk/Rq7MDiFKN3BuJ5XPAnIyQjjPi1YuU02QfYNBn/1RE4/iKBSGbTgivjI6Na9dmPM+vR5IibRezEoMpvgLOZ+mCv6vE9T08O3RvN+uDTMMW+auRW2wWKMb6KMoEOiIeQNrVqN/Jb8B3csujL1EKZRjeRyNa4eA1+1yE69ujBm7Jtro7noEH1Slrqx4cy8qUfMxFfKkQQ2B9r5tTHmqKHavAA+IkKAUWQZMiaQN+4w2YFnWWYqF5M4VfggsuUSwNoFijedTAujydqSvn1475UGBOOeD32PIUHUndoQbcbkZI6aZjEM+Fjt3uF5uURk5QgnVD1ki4GY+0Fngyc3BD5IZnGUA42nX+mePNJabR5fM4Ir64ofhGFDuoIcKzlb0neyCSDp14vzB9brvhi9kutKr0gs/LErMzkH562XJDCzWh0DwSJ9EO5fwVDvNLj10dEu26jVQT+Va2iWTU9vd5ZWolPCY0cLmEy4zSdyKrM6FXb9dj+ahUAJjJ2W1BTZRieq1gzrajxL/LgWgWIE00TRjhO3LBZYgtRFoCFc0kON9eRMsyPCLbeaqTMKkP1F
  template:
    metadata:
      name: timescaledb-db-connect-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth
