apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-connect-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgAJfFll4ocxhuZ0qOCK4TyiwOuy7xOTR3xJ5AZvb8mX1f6NFEhHJsvVJe0G4il7JCddxdVEeTcjqwGQuOzt0edBrb5HZHGTvUPL7H2aDgK51J3t6KTq4Nvnmsf+kAPBdZgRTW6AtnsxcY9ae6tqplEELeqTUqCxsph7F/KnWYYJTX5FLbP89lA6vhBO5C9brFu1iaVREiqziM1tn9Y15YNrl1uDP+rlpVgpKwyjLos0xbQduJsfdg4oZiI8Pkb6mt7pZOZwJgaKt+0qfv0l1nETzFTDOao/bWTAVLn1oTK/k18hxFKdJu7gxdLkfx12v+EetY0j4q19zCm2I09sf315M0r9npngqrZgDcvvavCK9gfj1MXuLZvw51ErhgaVt/yaB5lmAeiX96wUPaVytwjdZetQH1+zc8ZPlZPjViW/IhFVui94Y9WnY2TLRE84t2w7r4+G/yGwKDbLD4u0eSUDLzJKYpUyHle8xY3siSlM6Ql3ZaCt/3qk664gK0BWjdJ8gDNOABPhOlwwudenkXBvSGhddUeg7gf1V7AgImWkWVVyHJKr9W8j2HLelTmTX8omsmFsGfGf+AC4U4Nx4Da8Zq8wVB5+8BATeZgGXQfXMQtAUATAHp86dgYEKrDbfWMqqFEWFiK6sQfYXafX8MPj5LAKHSpZaMU4iMWKvveRy3nrvbEsKIcCVbFKVLlK2ZXWtWuZHNCAxLWqIrft8igEn+g7vk/5rob01xnwtOz1FQ==
    username: AgA6qomVdnkcyV9g1LaI+erZQIyEQdMDWKw3Ya2p/Qx+tZWP+FnbcJvQdpVfZe6svhUuY3zHANYgEck3JZFWP9KIFPzKM46m/1mNAVyIcTKF7XysmFFuW+FpSUVWuhB5rI7KDTemRUjdoRGY2bzcqWDT/hKdjj7Kg5cy8wgJaJ2Ki0W5I1dzh6NIOKJkR3rFqydFa9JZAxC9zN7YOI1ey7LhslARttd7rOCAuPe28m4tdiJGJWlz0hhPa+MEMrJ4AlkdQa62NeIeGob7caNRcbHgPGLxYm8+R5SEN6OPKESkoNZcc9klNLXUxI6h58C0gcx6zE2xjdaX0YrXktneXoPo/a873jtddpr+mXl6OPPugzqack3CH8g655PJXIN2MVC5/yPzVBdUebND5gjjSDZ0wI1FQ+jtvZCmbo45KKvoN7t9gWDvPcz0tjhQmZd2Tf5dg179whZ8HStDfJbT2OmHihh+HjH5YwoCZIoZDT53p9RhQwON0V3vmfBfLHIrmJdNziWKcM6c8IboP0NRY2WbVIstDvf0t96VfHpxVU9iGP1W7Bf9ekYKn/Dhpv1RWFTSNBoQRqjinkj6P1zEPRm2gWLNWjr9ocblBnd3A2y9gmUAtO65hIbVjxFUxVUKbOGN2XLG7no092WC9kHQmEhgcWqBfKRMCxrVmecRZichhNxmvhbR1/RUFG9J8fFHr7UR6QfWj0u3
  template:
    metadata:
      name: timescaledb-db-connect-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: timescaledb-db-iot-mcp-bridge-ro-secret
  namespace: timescaledb

spec:
  encryptedData:
    password: AgBQQkk5C1oaBmx2FbcuM6jHu0BRnZmKEzsPa/VGoCrxV2ZZZ/Tc/k4L9f3kjKrWeea8C/4a25+Zwdz4mMa1Q9t13sTdkAjSy/CcNBMpFqHexf4mN2PbV4/vUiE+Vw6HzYJlLcXL55njeWwRRYzipRSRNzBd1I7dWrbHObo/WJfGSeaPttx7e5LlK8EJIJS+zqPxXdMAN/Xrm3SkGlGB2kJnRgvzn6CAJ9V3A3TTH1XBa8PbGYegBjvz3yk262PDAYqW1DqbvjwY+t4FBN3xw/7XhNt+qey4qNKBTedTjRPaVQEQqdGe2DGqdEwiCn+2POCcOLUxQWFU6uNdE1vJArkdKkTvItZjt2VTzazmhowo9fk0QHSU2Jh+wWuDo53j6CNN2tREFUv8m+Dtx2qnsYTvyrV8gf4AMCXd50iN6nZ7N/c1Ts5M5+Bb12MO/PgwjKgUj2V4AtKl2jjvJSR5V4bScOwdW8+kNK4I+uzdYmfw4vSDXyA3BI91WenEwlK3/eR2DWzikzNcT6CkcxRuG8sHGfuwmjcsGqCTaYZwpm/45hVuc+dhGAAAorIfLChmTTJXL5zNsYPWR1shpUrywqMTAzRbXZNqispY7npgW65l8gE4T7xVFcvCFGJ2ErdvMSHFamCfaao4/2bAEWhJ76apuA8JA9zW0s5aBcnpRUlP63pWFIviZvHiK3BRw2xRJOndE+n5msSfMHGOFl+qaVX9HY85+I0o9u1zwv9CKMWBNg==
    username: AgBLTWOXGuLLCdRkQvFS3a+cqfN+9FxDG2fQC4AEfft6dcG1DvLOFX6JZdT8pW2veK6RgRwOGmEJs+7+ZUbTubtoItykOpnk0zXur41QtqrtwgM4RPzm5MVn3REVsA5WwZ0yDcUNPqH9VVJyHAxuhjsAhx9AbZ9UxZM9pq0sfXihnJenL7eUiHii0pB7cydhHtB09nPBcuvH37nCdPw7ETKoYpFcKpaTRyLYRoXooGeT7CbYJXKxRDz75n3CvVoeq+zNcPsCdujY/n/0VJwp5zRIUxm7/ANnXkhJ5sVoOvJuUpt1zxK5+dv1xjWWL21xNIPD0ZPpMmUQ5WGqFzulhoC+GvvOHobr5/luBEYPasWLho+SkJjpD+usev+eksfTTIsj+LM/o+VoRz/jwYX/Kt8ktDEfSZBoF/rxqKAKCyzFNZEfHgkPkuGD62Z7hil8/NRX/bvqNZQ17llXwCUYzSKKna0uaRrQD3GiCpx5ryhIuySMgOKn0HCVgVUIHCOiAP9yxwKdDmXjkwqhj3gPe4yNvOjQglcvN6zJHeXjdtY2tIXZA8nKOzZTwwUtPiZnaHx0T5FzLcivHZ6BpP6hGCvBsYuLTPWKv4oDVMRJmhb5h7j7f3mFz6lP599evqG1BDbYYhGpkOUjAYN6KEUCuHJYqYYL1obNkXLYPBiRbfDlw7G+gCwmKjgTlKhzqC+R803+ozcval7RAe0LaJt8vXADZA==
  template:
    metadata:
      name: timescaledb-db-iot-mcp-bridge-ro-secret
      namespace: timescaledb
    type: kubernetes.io/basic-auth
