{
 "title": "Gastherme",
 "description": "EMS-ESP",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Warmwassertemperatur",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curtemp\")\n  |> map(fn: (r) => ({ r with _field: \"Warmwassertemperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Heizkreispumpe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"heatingpump\")\n  |> map(fn: (r) => ({ r with _field: \"Heizkreispumpe\"}))"
    }
   ]
  },
  {
   "title": "Mischerpumpe",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pumpstatus\")\n  |> map(fn: (r) => ({ r with _field: \"Mischerpumpe\"}))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Heating",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"heatingactive\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Heizung\"}))\n  |> aggregateWindow(every: 1m, fn: last)",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Heating",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"charging\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Warmwasser\"}))\n  |> aggregateWindow(every: 1m, fn: last)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Temperaturfühler über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outdoortemp\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Außentemperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Wasserdruck",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"syspress\")\n  |> map(fn: (r) => ({ r with _field: \"Druck\"}))\n  |> aggregateWindow(every: 5m, fn: last)"
    }
   ]
  },
  {
   "title": "Warmwasserdurchfluss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curflow\")\n  |> map(fn: (r) => ({ r with _field: \"Druck\"}))\n  |> aggregateWindow(every: 5m, fn: last)"
    }
   ]
  },
  {
   "title": "Therme über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"setflowtemp\")\n  |> map(fn: (r) => ({ r with _field: \"Soll Temperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curflowtemp\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Ist Temperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rettemp\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Rücklauf\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switchtemp\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Hydraulische Weiche\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Warmwasser über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"settemp\")\n  |> filter(fn: (r) => r[\"topic\"] == \"ems-esp/boiler_data_dhw\")\n  |> drop(columns: [\"host\", \"topic\",\"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Soll Temperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"curtemp\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"ems-esp/boiler_data_dhw\")\r\n  |> drop(columns: [\"host\", \"topic\",\"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Ist Temperatur\"}))\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fußbodenheizung über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flowsettemp\")\n  |> drop(columns: [\"host\", \"topic\",\"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Soll Temperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flowtemphc\")\n  |> drop(columns: [\"host\", \"topic\",\"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Ist Temperatur\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Brennerleistung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curburnpow\")\n  |> map(fn: (r) => ({ r with _field: \"power\"}))\n  |> aggregateWindow(every: 1m, fn: last)"
    }
   ]
  },
  {
   "title": "Brennerleistung über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curburnpow\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({r with _field: \"Brennerleistung\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Mischerposition",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valvestatus\")\n  |> map(fn: (r) => ({ r with _field: \"Fußbodenheizung\"}))"
    }
   ]
  },
  {
   "title": "Mischerposition über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valvestatus\")\n  |> filter(fn: (r) => r[\"topic\"] == \"ems-esp/mixer_data_hc1\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Ventilöffnung\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems-esp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valvestatus\")\n  |> filter(fn: (r) => r[\"topic\"] == \"ems-esp/mixer_data_hc2\")\n  |> drop(columns: [\"host\", \"topic\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _field: \"Heizkörper\"}))\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  }
 ]
}