{
 "title": "Gatus",
 "description": "Gatus — automated developer-oriented status page. Based on https://grafana.com/grafana/dashboards/24379",
 "tags": [ "gatus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gatus_results_duration_seconds", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Successful results per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[5m])*300) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total results per 5 minutes",
   "type": "timeseries",
   "description": "Number of results per minute",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[5m])*300) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Unsuccessful results per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[5m])*300) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}