apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: node-red-tls-cert
  namespace: node-red

spec:
  secretName: node-red-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - PLACEHOLDER
