apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: node-red-data
  namespace: node-red

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: PLACEHOLDER
