apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: node-red-credentials
  namespace: node-red

spec:
  encryptedData:
    credential-secret: AgBdQSGS6xOx1B1sf5Zkp4OxzHwnSgGDYSNt7WE/CUe+qGi2Kw6fhrr4sxfBc7o8U3dBTy0lpzHx6ovmrM58ImZPUimhQ4V7pehz/WEddaRfSFwJAnQIrjSJ1fIaILfwIJShHilL+O72Amz01pYUonNGTLtcgz7ySZeiW5R72B3zt/ffep5nE0+ABnnFXdxu7HgBlwJgSqpEFgt/WIhLQM6N7HylWPGjvcYQWhxL3uihl9d7Y31hqT6LMmjHT1LCtZi2S+KPwgcFnvgNs+45xMVF7anKvHbcb1v16jARIZIJbJuFxjXrpLJOZhuIH3/63J7/qNPnjs5ML9TlH0gdo+rpnzCdUjHV0AH/3DNT7ADLPzook7aq9J+4Rd9vFvj2LyK7PbL3Mzpl4T1dLT34+fcrznyfcsOKQwtUiFX68EjslVkFf0QnZ9LNCkEN61w7yX0k11i86oX+lCSW9T6fFyiyqeCsf5mdcZB7qp/T4gI6+gEnikh/nAjRqGYnx9pY8sl21VmjlpgWRVyG84Q5lV+impZylVmTdBUJR8JDcztQ7Wf2WG3c2Z4AzfzBSNkVD8XNQ6OBUvb3XqJWLREpC4mig4LAWH7f+8evEbNrILD/Vi2kDBiF/iFGa820wNEmmu3tFC6Ta/cVJVOIACcrY+1jLmW+H2mInnDktulPDETkx7BV3C7nl5x6+wmijZnuoBy0Y/e4PQzLGltO+mm9sGF/sYF7L5UMGu7lQlWxvjFQPoRpdujEJF4choyF4Q==
  template:
    metadata:
      name: node-red-credentials
      namespace: node-red
