apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fritz-exporter
resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
  - ./sealed-secret.yaml

configMapGenerator:
  - name: fritz-exporter-config
    files:
      - config/fritz-exporter.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.app: fritz-exporter

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
