---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fritz-exporter-credentials
  namespace: fritz-exporter

spec:
  encryptedData:
    password: AgC51hpy6CnUNvRz4H8meAJ8XR3T+89ZMu7UkoHDeu7GaELo8lGHuT3gROtHhn90YBUCZyuzus/rwR3DkvuF8t3tv6tTM1B86a9212GSysbqpwuYE9387c78z6iFhDxNP9BP1dk+RW9KzymLwanuU9MDSV9MzoI04WSpLYaXWE8Lpf9fia5gKsGBzlLJHnWITA5Hx2KWID+jatYBbgQqD5EjbKTNlLlyVpXOGxodBRfCWE23LhHZsQez1qvdU3fJGsX2YMAkkn5lYcgWHZluEJlQmTWIGftCmTbZFNSONZYC5YL0pkNAjv0Nx/rWl+XYqTkVHZoEKeZ4pbwFsUN1HuxY1bBcJTFRkhIBFXUaXmJagdzHzc27CXoDr8bMkpcdECO6l+SpydLvkfSOPkc6oxDGjimJE4QxW6WZq7lxO8hiL45Sj3jMqk5GP9NedT8cFdfYvhoSwtyrm9EOR8ZcB8Ntk860wgonJDrk0/HE4ARYgMP/Hx0pYXQo87lc4dQYo0Jw6dlXWM+3gob0X1cmPp7a6EUlv5LGThZjE/UNkYGq9pVqKvTGyhjoD7eq1N815Zb/lMneyBme6cHLwGBBRNcee1CjBGRnkV+PLiEXQTA589MDlknSDQt9SPSbSshTWTj1yURjeLFetOALorYYLOW6mACmry+Eau58BOISABQcnC8YsrHZpB5WHxSBfx+ihO6U3BCJornd7lIGfkQUXm5M6aUr2g==
  template:
    metadata:
      name: fritz-exporter-credentials
      namespace: fritz-exporter
    type: Opaque
