apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: fritz-exporter-credentials
  namespace: fritz-exporter

spec:
  encryptedData:
    password: AgBYJr1oPZY7XAHj8em2U1JTPZBaBwEpBelgP2xoVy/dOFkVat8JMp5WOAXm14F4vbX68J8rPJK2KL582qgZC1G7LOAeW5c+OpcvLOSFCtg9fVTs3R02NYIpwih4iKIKaCRIKSRMFxmJHKM0YP89H4SJRRmFSjgTyW+UWMruxmugTMiuq3wDCfRVrAge5Fbzpuh8ohibV0gbGN3qIu+uZfKptKRoLjxBNBEyWonKCT1WZVj4tily62tBL9y1DtPzZRlcLDZxDbTeR9LNbCmLu/6/EeAdY0xijMYPs9N3mJX7r+q8ilun0efk3EUivYd0U121oKTCxRdYYnQirsouiEephD+D8mOG+0ZeafDlww3jjBsZMIhnb8b5IwuAacAfR7n/DB1dQM1qzRdWTlL9z8xezpYxwDckDysyRCvgzfbeRSne3SepDRGTShPotFgcgJDirQPd85lc3jLdJXVx2SbyoMjgq0jisfHqZeZw+RcbawuwKm5ivcl/NxbWSbNs51z9vbK1aldi3xijeJO0RS/JwEzWqljcOE7hTHT/GqXTw/DPcLZykpdSNE/LsrnM6HOI6+14JvI6zACGKxZaopApUBe8Z0+59ZVcUJMOWgx868UxXDbclCTUe45edAUbzFDZCD0sOv7YMG2eQZA+8E00VsuPmYlK9jExnqRwORVcM3Z+3qEAgA5ucEC/yRF8h4jEeSgyd6hO0JBatIl1W/8JDWs7LA==
  template:
    metadata:
      name: fritz-exporter-credentials
      namespace: fritz-exporter
    type: Opaque
