apiVersion: v1
kind: Service

metadata:
  name: fritz-exporter

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fritz-exporter
  ports:
    - name: metrics
      port: 9787
      targetPort: metrics
