apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redis-admin-credentials
  namespace: redis

spec:
  encryptedData:
    redis-password: AgBuWCfEy9vD8Bhct7GAxhM2x3WYIFEEul/OdRkCQTiWrTQJB8vTTnp3HBl6Pag76VgVE6UNe/mxBGx/PH1nU9GFTy5CreRhCq7j4QH6gzBKrHDNEBp2pB7jatPExo3dBxOt4/396Dzws/xl11lnD1p0xHUmZB+JHfgiO4l+0hoO++s3g38xKfO3pjI+Hpolj50wrOyk5wB0PTh2dl5RHDhBI9U/fpsAyLdt32l/iLz5PEuHWfrADbCPlPZSxmTe+OCrz3pxFV36ClSb5bMggGxeRxAQSfs6DVcdMiN5hWkWv913TWZNHu3YZTLe3cfNDhz7S5SQortS8HoXco+zpYOFIy9BUpWOMRN1SV4Ulg0mc4A5shzCl0eFdjjKE/6tuqNKxYImWOO8qjHGq+v4XkqILEu+B5k19ymkbvOllF1L3tEEfqgDWw4DqymDzSugo+C55O6NgPHhk4A7SVSv46tnyvUjd+L28rLiBCcFMYRd/fWQcTap34lb332ilikJNwnkrHkYpHSuv/q+n+x1FoOMnz9zT3siMJ+H0pBGew+U2xTKuTACnuTjnBC+d68tn+q8toENj9oo1JWXvKXVY8lfcxM6acy8jihYVcsQLOgBy3WbvqE/0gd9Y+kTYDFT5nqgJw6lAwSEOtEDaH9XS/ZPZ/i+CFUAW4OFVr2JZorXdZrT3AxcRfk07/lJMHsC+xRYnorB0BYNMoXmVfger6Wm5yM4/w==
  template:
    metadata:
      name: redis-admin-credentials
      namespace: redis
