apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redis-admin-credentials
  namespace: redis

spec:
  encryptedData:
    redis-password: AgCbm9Qc34HPGfAPTYcvD5a6+IvgPT0yBvbxmtAWsA2734RsiWjrPulaAioc6pCgF11KQCjZFIMhF1Oj2ZphVZc3Dgir85HyJBVah+k1PyI52Aw7fGQVXZai+1pP6fX9imTp5x5BO9I4jS6GxHVnQ55sTAWdmE7Y23iwgBGSoWPQ/KuiPXC0EcoooBTM1HDlVLdvbETrlxm1jEJUlfJUF8R8sZcPvB0LgVwbed3La7MFbWaUWvVdXA4ngr5xY8+hZGbOtzWVZjjKVXn7YADtoSNoUCQjmWF3jS4W4y6XxsrjiG23XRsZl4n1Ny4eGipbUiNq5YjZxHgtYf49UL/+/HsHHspyXkXHW0IWLsjNn0Xv0T9+KiPL0rP0Cz5Lxrv6SCgJVWpRtO5TdX84PeIXIaEaaDJKMnIaSlpcqkZFqqVuCU3qeEs3/V1rBN+WBa4xpBH3WapGm9QeDp6xMDfSK20UT/FLnXNBYZNVrW0eFvS7ChVmePMLHn5K20LGQXwV5N4gdIgNdo5JHy3M8UutcHwmV/L3W5Biqd/PobXDL/CM+sDc+z6oQUQR+Z2w1gfxNMursFXxEep+TQ0AG+HIDe6bGFN0ZOZqAc3C6f312pTguvDLEC9xzCUPrATzLbOiBpjoeS5Bq/DwXMSlcbBTF9c8U0vZT4XEkFBnDs/aODh+0h8D1Y0Dt7XCJWlZ/99NaICuafrwAAG086VeYnkeBQW6HIazRQ==
  template:
    metadata:
      name: redis-admin-credentials
      namespace: redis
