apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: iot-mcp-bridge-wikijs-token
  namespace: iot-mcp-bridge

spec:
  encryptedData:
    token: AgAUiPkznv7/G4DjhjfiogDHY+NW9IgwHV3dVjWtmqkFu1G8zzYz6i3vDduD/PK0nQ2K4Y6MOnaxeBpQp/pKoPRLQDTIMKUZo2an1kFN9Fl/+YfhroVCNDVIgyivf/KnpaWlC5+puGyp4aukeYolbkSdXGPNtyWyCp9wBGF01y66F7XnuIoXwUUDQObrmkRfOvOOfUQmYIxOqc4YVAJuBMZWrCDFEXNqrRvqOxq/80fRuDivXck76WcvNtnpF988KL4vCw6GowPqY2uiaSgF0zAvKklAeUFn3RxWtM/qcbfIvPg9yPQG3zU84MFG2ND16MFydzJ8V0eiPXPq1TdgA8MTCxbmsAK1/LddC6JgjGF3beJl3lymMq/xvu0IqoqhYVlz8y0bVDlpS01FQ4BsRrNJ0cN2iwuDztBRev0BU4KurIJHmOxFzbuoMU/W2HJxSUA//Y3m1HEIY2UM2IwR8WOJpbNtzW9XtwAxUeQySEuwBjapqwCEhJs24zK+ja3tLKH4YktIFCQr0yO+dwE7zVNnFrYo6WrHgDSl0cTI2oZEkjNVbSIE8vuJ7QbKHzmtuLqizv/Ld7QLDZne0pRWSpJN9gabY9lbr0toPKrUmf/dWbibmDwREOfojBev5KEcQAT/yoy+AT91IZnb1Q1QhjxpLtoaevTZtzJAbDJskcD9zmabqlu4W1aRSNQ7bXcUsJ15rs/UHTn5WnqK1T3SLCGcYFsdtdlXbjSnEs2/p5NS1FnjwGa606Dvuc8R8JotL6ctc4ap+OU3AoxfR1/G8rVHbMAb81RliGl21GzwXQyCHWYYm/o6GD7shgmH4K/abianWqhW+Rddz32ikHeigWhkQO5IEqLT5/x2yl4uqiZeCHIt/J2STjRrFmOzMnsoYVFmILVJs6xVo+9wMnRTdMvWONUJkS3Ndhqi4Due9qCW96HUdSC1Gi3iWjlrEhYiF2dDrb8twoE0cFFqFYSNbaaj+TIIJ7Vy9AANEya7dp+Escc8w+TYNaa7z33HI+aUwgIbjuROvYtS7ZsbFWtthu7JEt7sBKMXnRjbP4s+3Rz2/DMq7ZoQyrEVSYInPMKzc8SwuNdGmTaHFrAfgKFrnY2XMiei7Xj9sW4I416M5Op9nGgaRZlNgHltLc7X1fcKgRH0zSSXWlQskv/MfCVxHwiTOqbD5/LfZLd9YzmavoylAMFZSlpPXpFQb6HjHma7D5EwkUjdVn9wXItt+qAVOPwjCulNZ7f82oZL+g8Dg2vbLLFGoQJ3vOls5alzqe24mRsJHj5tmAZKOCkaK8t7nBmh8BqOOcW+F8IiaYyWTacNOmxP/a+c59/puIvB4JHpG2WQnbZ0RdM1EOg1forNJ+CLKxUehyuy
  template:
    metadata:
      name: iot-mcp-bridge-wikijs-token
      namespace: iot-mcp-bridge
    type: Opaque
