pve_cluster_hw_mapping_usb:
  ups-apc:
    comment: "APC UPS for power monitoring"
    map:
      - id: "051d:0002"
        node: "pve-1"

  knx-license:
    comment: "KNX License Stick"
    map:
      - id: "2a07:0102"
        node: "pve-1"
