pve_cluster_users:
  users:
    alexander:
      path: "/"
      role_id: "Administrator"

    proxmate:
      path: "/"
      role_id: "Administrator"
      create_token: true
      token_name: "proxmate"

    homepage:
      path: "/"
      role_id: "PVEAuditor"
      create_token: true
      token_name: "homepage"

    omni:
      path: "/"
      role_id: "Administrator"
      create_token: true
      token_name: "infra-provider"

    ups_monitor:
      path: "/nodes"
      create_role: true
      role_id: "UPSPowerMgmt"
      role_privileges: ["Sys.PowerMgmt"]
      create_token: true
      token_name: "ups-monitor"
