apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dhi-registry-secret
  namespace: sealed-secrets-controller

spec:
  encryptedData:
    .dockerconfigjson: AgAQhKXDI5yPBNXcEt8herIwP/x80GCZKTxmpKWk4QWX3JIM9tPSY6wzkxlgV8z39d4KbSpI17FO72LX0zl16xGsTMHnen8Xj9uuF82RNbVdrU+pW47lNpRT3i9TdrT1mIJLHG4CFs3f+uzOoqrqLMoJDbvOFC5nnw+pzTWUfYuAlawEg5XnaWPhVoUOu78SkZVYbdEzXRrhpHHN4GpW2WI8yrIt0bj/L6zeMddECZaFWzRhZQ0knjHPbnEL3kG2OAgK7MWH5jOjHEbnESQw2ZCfOJOubkRRyX/G1N+Oj5S35VA02ZWefJ9Se38fMtFJAdyxmH2ZiOr7KAeNGgos51upq8+czPmwcuAIf2P3wc3XS3YQgLZWTeJxct/CTEfo+bEe/sWUnF7drwYuyAdq/kq6MonFYK7uTVSIe8fIfcv5eAjqLwkispBxgK+hY7YjakfmmuvtjJHcZ+wIj+83dZnwVMNzEvHvrV1+4vkCwBTxfnkGWDVjawgVSX2uFGFL9Y5phkI3FZzwQfqNAgSQI/TzbXD6I1gMrjeAI9CYv2J/Hjy9Unw1vLqC+eU7BpOudf0dBrnKUImsAP6Rm/ukytQmFzxTarhqpnseqrBMe8oVtuEOBy+88t0s+OO2BFQ9h1mtjmdz0d9qKrl1vPz0Q2h1ziu386d617IcvrTZUzR39CsThA6Z9TTAqU8MoMKJIXL9aUbf7WuxTDm3G1b+d9OP2aK24ydujr0xoiGNeoAWPsQ6QTa71cGRvvDWTznW1jCpxY2wSeNeEy4TxU1COjn2dCxW63cXK+n0fbXMdTkvOA3AMc8ELps5A0hXmBaZrErc0agSFs0bXBGC/Nzlss6NpoVJaNDvYUQ5Kr0SRAmxhfVYSs9zfDAyVS3n5w8GpJw1IVUDtYCv
  template:
    metadata:
      name: dhi-registry-secret
      namespace: sealed-secrets-controller
    type: kubernetes.io/dockerconfigjson
