apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: nats-operator-nkey
  namespace: nats

spec:
  encryptedData:
    nkey.seed: AgAkcNATu3mGfQfFdYEc/K05VShYDymcwE9fop7UvB2+83AqBXd47bs1DE8wN9VUPc+rvvy6F/SmFDEu9VbU5rVozQynqcGQWmJOE2/WYqfKcjBUErz1oPUBS8Vsa5Ya6s/p/0MH4Lri4UtjagyNLo43GR2HfYlG/gfdXbzRgM9g+We3I8PQGI+2m+t6BwMk4t8eSFVpzO7K2Q3RkGX5Ilr1mkIhfSrpQe/UcYv0nI7NdzGldqLcSUOI3sg3E2rNAPJ2HFBRszJsAWTE7epZgl8qaJ2x3dSaVpnA1+25h4pwCSTlPntb22bLDabTpGMG9OCEuVrZWx7b3rDI3E59X9h6r/CKAobOr6wFI8hPLhJQOsO5cQRz0gAZKhZ3SITPcJ8EEcyl/mwAK97YqtVQENNT4drdxDtMbL6LXY35ZnsKeNWgYlGBWPPIGQw/QD0CD3CVNGnkMyakq2O/bhoEgutPqtPubUh99o8bk4u9Cr+zwKtWNXNx7LANK/XunrllD3+UFJOCX2XVH32Jk/YJh1LPD3jgy137rzX87sPwEkdVNrt2d630ILRg/NpjaTs2vDBWA3t6Lhy7QTQ2uLS91xT87G2Zw/lANLTifW71+7DY3MSNofdbJGXZK9PW7DY+af83nWaYjE9AAbKH0ECukC+fMn4FIhMqdGPWkvX3dpB3JRVuqISoiVeeLW5nOSywXPKY1PcNmdG+SXwiuxiirXNCOWsUe22eNk5QukhX5COdjt8+5Y53/HJNb4BEhpEvJby8U/JZ2EN0YQnI
  template:
    metadata:
      name: nats-operator-nkey
      namespace: nats
    type: Opaque
