apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: argocd-server
  namespace: gitops-controller
  annotations:
    # ExternalDNS configuration for Cloudflare
    external-dns.alpha.kubernetes.io/target: udm-pro.zimmermann.sh
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    kubernetes.io/ingress.class: traefik
    # Homepage Service Discovery
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "GitOps"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/icon: "argo-cd.png"
    gethomepage.dev/weight: "1"
    gethomepage.dev/href: "https://PLACEHOLDER"
    gethomepage.dev/widget.type: "argocd"
    gethomepage.dev/widget.url: "http://argocd-server.gitops-controller.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`PLACEHOLDER`)
      priority: 10
      middlewares:
        - name: chain-standard
          namespace: ingress-controller
      services:
        - kind: Service
          name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`PLACEHOLDER`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      middlewares:
        - name: chain-standard
          namespace: ingress-controller
      services:
        - kind: Service
          name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls-cert
