apiVersion: v1
kind: ServiceAccount

metadata:
  name: argocd-sa-provisioner
  namespace: gitops-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: argocd-sa-provisioner
  namespace: gitops-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: argocd-sa-provisioner
  namespace: gitops-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-sa-provisioner
subjects:
  - kind: ServiceAccount
    name: argocd-sa-provisioner
    namespace: gitops-controller
